import argparse
import re
import sys

from kg import GRAPH, REF_PATTERN, ROOT, STEP_PATTERN, VIEWS, label, load, module_of

HEADER = "_Generated from `docs/graph/graph.jsonl` by `scripts/graph/kg_render.py`. Do not edit this file; change the graph and re-render._"
SECTION_TYPES = [("Feature", "Features"), ("Flow", "Flows"), ("Decision", "Decisions"), ("Concept", "Concepts")]


def prefixed(obs, prefix):
    return [o[len(prefix):] for o in obs if o.startswith(prefix)]


def others(obs, used):
    return [o for o in obs if not any(o.startswith(p) for p in used) and not STEP_PATTERN.match(o)]


def mermaid_text(text):
    return text.replace('"', "'").replace("[", "(").replace("]", ")")


def link_refs(text):
    return REF_PATTERN.sub(lambda m: f"`{m.group(1)}`", text)


class Graph:
    def __init__(self, entities, relations):
        self.e = entities
        self.out, self.inc = {}, {}
        for r in relations:
            self.out.setdefault(r["from"], []).append((r["relationType"], r["to"]))
            self.inc.setdefault(r["to"], []).append((r["relationType"], r["from"]))

    def targets(self, name, rel):
        return sorted(t for r, t in self.out.get(name, []) if r == rel)

    def sources(self, name, rel):
        return sorted(s for r, s in self.inc.get(name, []) if r == rel)


def module_members(g, module):
    members = {kind: [] for kind, _ in SECTION_TYPES}
    for e in g.e.values():
        if e["entityType"] in members and module_of(e["name"]) == module:
            members[e["entityType"]].append(e["name"])
    for kind in members:
        members[kind].sort()
    return members


def render_overview(g, module_name, members):
    ids = {}

    def nid(name):
        if name not in ids:
            ids[name] = f"n{len(ids)}"
        return ids[name]

    lines = ["```mermaid", "graph LR"]
    lines.append(f'  {nid(module_name)}(["{mermaid_text(label(module_name))}"])')
    for f in members["Feature"]:
        lines.append(f'  {nid(f)}["{mermaid_text(label(f).split("/", 1)[1])}"] -->|part_of| {nid(module_name)}')
    for fl in members["Flow"]:
        lines.append(f'  {nid(fl)}{{{{"{mermaid_text(label(fl).split("/", 1)[1])}"}}}}')
        for f in g.targets(fl, "implements"):
            lines.append(f"  {nid(fl)} -->|implements| {nid(f)}")
    for d in members["Decision"]:
        lines.append(f'  {nid(d)}[/"{mermaid_text(label(d).split("/", 1)[1])}"/]')
        for t in g.targets(d, "shapes"):
            if t in ids:
                lines.append(f"  {nid(d)} -.->|shapes| {nid(t)}")
    lines.append("```")
    return lines if len(ids) > 1 else []


def render_flow_diagram(g, flow):
    obs = g.e[flow]["observations"]
    steps = [o for o in obs if STEP_PATTERN.match(o)]
    if len(steps) < 2:
        return []
    lines = ["```mermaid", "flowchart TD"]
    for i, step in enumerate(steps, 1):
        text = STEP_PATTERN.sub("", step)
        refs = REF_PATTERN.findall(text)
        text = REF_PATTERN.sub("", text).strip()
        short = text if len(text) <= 70 else text[:67] + "..."
        extra = "<br/>" + "<br/>".join(mermaid_text(r) for r in refs) if refs else ""
        lines.append(f'  s{i}["{i}. {mermaid_text(short)}{extra}"]')
        if i > 1:
            lines.append(f"  s{i - 1} --> s{i}")
    lines.append("```")
    return lines


def render_module(g, module_name):
    mod = label(module_name)
    obs = g.e[module_name]["observations"]
    members = module_members(g, mod)
    out = [f"# {mod}: knowledge graph view", "", HEADER, ""]
    out += [s for s in prefixed(obs, "Summary: ")]
    doc = prefixed(obs, "Doc: ")
    if doc:
        out += ["", f"Module doc: [{doc[0]}](../../../{doc[0]})"]
    out += [""] + render_overview(g, module_name, members)

    if members["Feature"]:
        out += ["", "## Features"]
        for f in members["Feature"]:
            fo = g.e[f]["observations"]
            out += ["", f"### {label(f)}", ""]
            out += [link_refs(s) for s in prefixed(fo, "Summary: ")]
            for key in ("Roles: ", "Parity: "):
                out += [f"- {key.strip()} {link_refs(v)}" for v in prefixed(fo, key)]
            out += [f"- {link_refs(o)}" for o in others(fo, ["Summary: ", "Roles: ", "Parity: "])]
            flows = g.sources(f, "implements")
            if flows:
                out.append("- Flows: " + ", ".join(f"[{label(x)}](#{anchor(label(x))})" for x in flows))
            impl = g.targets(f, "implemented_by")
            if impl:
                out.append("- Implemented by: " + ", ".join(f"`{x}`" for x in impl))
            deps = g.targets(f, "depends_on")
            if deps:
                out.append("- Depends on: " + ", ".join(f"`{x}`" for x in deps))
            dec = g.sources(f, "shapes")
            if dec:
                out.append("- Shaped by: " + ", ".join(f"[{label(x)}](#{anchor(label(x))})" for x in dec))

    if members["Flow"]:
        out += ["", "## Flows"]
        for fl in members["Flow"]:
            fo = g.e[fl]["observations"]
            out += ["", f"### {label(fl)}", ""]
            feats = g.targets(fl, "implements")
            if feats:
                out.append("Implements: " + ", ".join(f"`{x}`" for x in feats))
                out.append("")
            for key in ("Trigger: ", "Precondition: "):
                out += [f"- {key.strip()} {link_refs(v)}" for v in prefixed(fo, key)]
            steps = [o for o in fo if STEP_PATTERN.match(o)]
            if steps:
                out.append("")
                out += [f"{STEP_PATTERN.match(s).group(1)}. {link_refs(STEP_PATTERN.sub('', s))}" for s in steps]
            for key in ("Result: ", "Failure: "):
                vals = prefixed(fo, key)
                if vals:
                    out.append("")
                    out += [f"- {key.strip()} {link_refs(v)}" for v in vals]
            rest = others(fo, ["Trigger: ", "Precondition: ", "Result: ", "Failure: "])
            if rest:
                out.append("")
                out += [f"- {link_refs(o)}" for o in rest]
            diagram = render_flow_diagram(g, fl)
            if diagram:
                out += [""] + diagram
            dec = g.sources(fl, "shapes")
            if dec:
                out += ["", "Shaped by: " + ", ".join(f"[{label(x)}](#{anchor(label(x))})" for x in dec)]

    if members["Decision"]:
        out += ["", "## Decisions"]
        for d in members["Decision"]:
            do = g.e[d]["observations"]
            status = prefixed(do, "Status: ")
            title = label(d) + (f" ({status[0]})" if status else "")
            out += ["", f"### {title}", ""]
            for key in ("Decision: ", "Why: ", "Alternatives: ", "Tradeoff: ", "Since: "):
                out += [f"- **{key.strip()[:-1]}**: {link_refs(v)}" for v in prefixed(do, key)]
            out += [f"- {link_refs(o)}" for o in others(do, ["Decision: ", "Why: ", "Alternatives: ", "Tradeoff: ", "Since: ", "Status: "])]
            shaped = g.targets(d, "shapes")
            if shaped:
                out.append("- Shapes: " + ", ".join(f"`{x}`" for x in shaped))
            for rel, text in (("supersedes", "Supersedes"),):
                t = g.targets(d, rel)
                if t:
                    out.append(f"- {text}: " + ", ".join(f"`{x}`" for x in t))
            s = g.sources(d, "supersedes")
            if s:
                out.append("- Superseded by: " + ", ".join(f"`{x}`" for x in s))

    if members["Concept"]:
        out += ["", "## Concepts"]
        for c in members["Concept"]:
            co = g.e[c]["observations"]
            out += ["", f"### {label(c)}", ""]
            out += [link_refs(v) for v in prefixed(co, "Definition: ")]
            out += [f"- {link_refs(o)}" for o in others(co, ["Definition: "])]
            rel = g.targets(c, "relates_to")
            if rel:
                out.append("- Related: " + ", ".join(f"`{x}`" for x in rel))
    return "\n".join(out).rstrip() + "\n"


def anchor(text):
    return re.sub(r"[^a-z0-9 -]", "", text.lower()).replace(" ", "-")


def render_index(g, modules):
    out = ["# Knowledge graph views", "", HEADER, "", "| Module | Features | Flows | Decisions | Concepts |", "|---|---|---|---|---|"]
    for m in modules:
        members = module_members(g, label(m))
        out.append(f"| [{label(m)}]({label(m)}.md) | " + " | ".join(str(len(members[k])) for k, _ in SECTION_TYPES) + " |")
    return "\n".join(out) + "\n"


def main():
    parser = argparse.ArgumentParser(description="Render docs/graph/views/*.md from the knowledge graph.")
    parser.add_argument("--check", action="store_true", help="Exit 1 if the views are out of date instead of writing them")
    args = parser.parse_args()
    entities, relations, problems = load([GRAPH])
    if problems:
        sys.exit("graph has load errors; run scripts/graph/kg_lint.py first")
    g = Graph(entities, relations)
    modules = sorted(n for n, e in entities.items() if e["entityType"] == "Module")
    wanted = {VIEWS / "README.md": render_index(g, modules)}
    for m in modules:
        wanted[VIEWS / f"{label(m)}.md"] = render_module(g, m)
    existing = set(VIEWS.glob("*.md")) if VIEWS.exists() else set()
    stale = existing - set(wanted)
    changed = [p for p, text in wanted.items() if not p.exists() or p.read_text(encoding="utf-8") != text]
    if args.check:
        for p in changed:
            print(f"out of date: {p.relative_to(ROOT)}")
        for p in stale:
            print(f"stale: {p.relative_to(ROOT)}")
        sys.exit(1 if changed or stale else 0)
    VIEWS.mkdir(parents=True, exist_ok=True)
    for p in changed:
        p.write_text(wanted[p], encoding="utf-8", newline="\n")
    for p in stale:
        p.unlink()
    print(f"rendered {len(changed)} view(s), removed {len(stale)} stale, {len(wanted)} total")


if __name__ == "__main__":
    main()
