services:
  web:
    image: ${CI_REGISTRY_IMAGE}:${IMAGE_TAG}
    restart: unless-stopped
    network_mode: host
    environment:
      DB_HOST: localhost
      DB_PORT: 5432
      PYTHONPATH: /app
      DATABASE_URL: postgresql://postgres:Passw0rd!@localhost:5432/postgres
    ports:
      - "8000:8000"