services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Passw0rd!
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    command: ["/start.sh"]
    env_file: .env
    environment:
      DB_HOST: db
      DB_PORT: 5432
      PYTHONPATH: /app
      DATABASE_URL: postgresql+asyncpg://neondb_owner:npg_3BRCMxJ8aKdN@ep-old-salad-a1x7ae1e-pooler.ap-southeast-1.aws.neon.tech/neondb
    depends_on:
      - db
    ports:
      - "8000:8000"
volumes:
  postgres_data:
