"""
Issuable Certificate Models — Templates and Generated Certificates

Two tables:
1. IssuableCertificateTemplate — Certificate templates (Bonafide, TC, Conduct, etc.)
2. GeneratedCertificate — Certificates generated from templates
"""

import uuid
from datetime import datetime

from sqlalchemy import Column, DateTime, LargeBinary, String, Text
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import relationship

from app.db.base import BaseOrg


class IssuableCertificateTemplate(BaseOrg):
    """Certificate template for issuable certificates (generated by school)"""
    __tablename__ = "issuable_certificate_templates"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, unique=True, nullable=False, index=True)
    name = Column(String(255), nullable=False)  # "Bonafide", "Transfer Certificate", "Conduct Certificate", etc.
    html_template = Column(Text, nullable=False)  # HTML with {{placeholder}} fields
    color_theme = Column(String(20), nullable=False, default="blue")  # blue, green, red, orange
    variables_used = Column(String, nullable=True)  # JSON string of variables: ["student_name", "father_name", ...]
    is_active = Column(String, default=True, nullable=False)  # Boolean as string for consistency
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow, nullable=False)

    # Relationships
    generated_certificates = relationship("GeneratedCertificate", back_populates="template")


class GeneratedCertificate(BaseOrg):
    """Certificate generated from a template"""
    __tablename__ = "generated_certificates"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, unique=True, nullable=False, index=True)
    student_id = Column(UUID(as_uuid=True), nullable=False, index=True)  # UUID reference to student
    template_id = Column(UUID(as_uuid=True), nullable=False, index=True)  # Foreign key to IssuableCertificateTemplate
    html_content = Column(Text, nullable=False)  # Filled + edited HTML content
    pdf_content = Column(LargeBinary, nullable=True)  # PDF as binary blob (optional, cached)
    issued_date = Column(DateTime, default=datetime.utcnow, nullable=False)
    issued_by = Column(UUID(as_uuid=True), nullable=False, index=True)  # User ID of who issued
    remarks = Column(String(500), nullable=True)
    is_active = Column(String, default=True, nullable=False)
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow, nullable=False)

    # Relationships
    template = relationship("IssuableCertificateTemplate", back_populates="generated_certificates")
