export * from './auth';
export { default as apiClient } from './client';
export { queryClient } from './queryClient';
export * from './staff';
export * from './fees';
// Export specific items from masters to avoid conflicts
export {
  AcademicYear,
  AcademicYearInput,
  AcademicYearUpdate,
  AcademicYearDropdown,
  AcademicYearListResponse,
  academicYearsApi,
  ClassRead,
  SectionRead,
  ClassDropdown,
  SectionDropdown,
  ClassCreate,
  SectionCreate,
  ClassUpdate,
  SectionUpdate,
  classSectionsApi,
  Subject,
  SubjectInput,
  SubjectUpdate,
  subjectsApi,
  SubjectCategory,
  SubjectCategoryCreate,
  SubjectCategoryUpdate,
  subjectCategoriesApi,
  ClassSubjectMapping,
  ClassSubjectMappingCreate,
  BulkClassSubjectMapping,
  classSubjectMappingsApi,
  Route,
  RouteCreate,
  RouteUpdate,
  routesApi,
  Vehicle,
  VehicleCreate,
  VehicleUpdate,
  vehiclesApi,
  RouteStop,
  RouteStopCreate,
  RouteStopUpdate,
  routeStopsApi,
  HolidayRead,
  HolidayCreate,
  HolidayUpdate,
  holidaysApi,
  Trip,
  TripCreate,
  TripUpdate,
  tripsApi,
  Role,
  RoleCreate,
  RoleUpdate,
  rolesApi,
  Permission,
  PermissionCreate,
  PermissionUpdate,
  PermissionMatrix,
  AvailableResources,
  AvailableActions,
  PermissionsPaginatedResponse,
  BulkPermissionRequest,
  permissionsApi,
  StudentTrip,
  StudentTripCreate,
  StudentTripUpdate,
  studentTripsApi,
  StudentTransport,
  StudentTransportCreate,
  StudentTransportUpdate,
  studentTransportApi,
} from './masters';
export * from './students';
export * from './transport';
export * from './expense';
export * from './profile';

