export * from './auth';
export { default as apiClient } from './client';
export { queryClient } from './queryClient';
export * from './staff';
// Export specific items from masters to avoid conflicts
export {
  AcademicYear,
  AcademicYearInput,
  AcademicYearUpdate,
  AcademicYearDropdown,
  AcademicYearListResponse,
  academicYearsApi,
  ClassRead,
  SectionRead,
  ClassDropdown,
  SectionDropdown,
  ClassCreate,
  SectionCreate,
  ClassUpdate,
  SectionUpdate,
  classSectionsApi,
  Subject,
  SubjectInput,
  SubjectUpdate,
  subjectsApi,
  SubjectCategory,
  SubjectCategoryCreate,
  SubjectCategoryUpdate,
  subjectCategoriesApi,
  ClassSubjectMapping,
  ClassSubjectMappingCreate,
  BulkClassSubjectMapping,
  classSubjectMappingsApi,
  Route,
  RouteCreate,
  RouteUpdate,
  Vehicle,
  VehicleCreate,
  VehicleUpdate,
  RouteStop,
  RouteStopCreate,
  RouteStopUpdate,
  HolidayRead,
  HolidayCreate,
  HolidayUpdate,
  holidaysApi,
  Trip,
  TripCreate,
  TripUpdate,
  Role,
  RoleCreate,
  RoleUpdate,
  rolesApi,
  Permission,
  PermissionCreate,
  PermissionUpdate,
  PermissionMatrix,
  AvailableResources,
  AvailableActions,
  PermissionsPaginatedResponse,
  BulkPermissionRequest,
  permissionsApi,
  StudentTrip,
  StudentTripCreate,
  StudentTripUpdate,
  studentTripsApi,
  // Masters-authoritative StudentTransport types (used by transport screens)
  StudentTransport,
  StudentTransportCreate,
  StudentTransportUpdate,
  studentTransportApi,
  CasteDropdownOption,
  SubCasteDropdownOption,
  castesApi,
  TransportPricing,
  TransportPricingCreate,
  TransportPricingUpdate,
  transportPricingApi,
} from './masters';
// Explicit student exports, excluding types that conflict with masters
export {
  ReactNativeFile,
  ParentCreate,
  StudentOut,
  Student,
  StudentAdmissionCreate,
  StudentAdmissionResponse,
  StudentAdmission,
  StudentAdmissionUpdate,
  StudentDropdownItem,
  StudentDropdownSimpleItem,
  AttendanceStatus,
  StudentAttendanceCreate,
  StudentAttendanceUpdate,
  StudentAttendanceOut,
  CertificateRead,
  CertificateResponse,
  CertificateDownloadResponse,
  CertificateCreate,
  IssuedCertificateCreateRequest,
  ReceivedDocumentCreateRequest,
  CertificateUpdate,
  CertificateTypeRead,
  CertificateTypeDropdown,
  CertificateTypeCreate,
  CertificateTypeUpdate,
  CertificateType,
  CertificateSelectorClass,
  CertificateSelectorSection,
  CertificateSelectorStudent,
  DocumentOut,
  DocumentResponse,
  DocumentCreate,
  DocumentUpdate,
  TransportRouteInfo,
  TransportVehicleInfo,
  TransportTripInfo,
  TransportStopInfo,
  TransportStudentInfo,
  TransportPricingInfo,
  StudentTransportOut,
  TimetableSlot,
  BulkTimetableCreate,
  BulkTimetableUpdate,
  TimetableDataItem,
  FrontendTimetableCreate,
  FrontendTimetableRead,
  ParentStudent,
  studentAdmissionsApi,
  studentAttendanceApi,
  studentCertificatesApi,
  certificateTypesApi,
  studentDocumentsApi,
  timetableApi,
  parentStudentsApi,
  DocumentTypeRead,
  DocumentTypeCreate,
  DocumentTypeUpdate,
  documentTypesApi,
} from './students';
// Explicit transport exports to avoid conflicts with masters/students
export {
  routesApi,
  vehiclesApi,
  routeStopsApi,
  tripsApi,
  transportApi,
} from './transport';
export * from './expense';
export {
  StudentProfileOut,
  StudentProfileUpdate,
  StaffProfile,
  StaffProfileUpdate,
  ChildProfileOut,
  ParentProfileOut,
  ParentProfileUpdate,
  studentProfileApi,
  staffProfileApi,
  parentProfileApi,
  BLOOD_GROUPS,
  validateEmail,
  validatePhone,
  validateBloodGroup,
  validateDate,
} from './profile';
export {
  feeCollectionApi,
  feeConcessionsApi,
  feeCategoriesApi,
  feeTypesApi,
  feeTermsApi,
  feeClassMappingsApi,
  feeStudentMappingsApi,
  feeTransactionsApi,
  feeReceiptsApi,
  feeRefundsApi,
  feeReportsApi,
  feeClassMappingTermAmountsApi,
  feeOldFeesApi,
  FeeSearchStudentResult,
  FeeCollectionSummary,
  FeeCollectionSummaryItem,
  FeePaymentRequest,
  FeePaymentResponse,
  FeeConcession,
  FeeConcessionCreate,
  FeeCategoryRequest,
  FeeCategoryResponse,
  FeeTypeRequest,
  FeeTypeResponse,
  FeeTermRequest,
  FeeTermResponse,
  FeeClassMappingRequest,
  FeeTransactionCreateRequest,
  FeeTransactionResponse,
  FeeReceiptResponse,
  FeePendingStats,
  FeeStructureStats,
  OldFeeItem,
  OldFeeManualCreate,
  OldFeeCarryForwardRequest,
  OldFeeUpdate,
} from './fees';
export * from './communication';
