DEFAULT_ROLES = [
    ("Admin", "System administrator with full access"),
    ("Teacher", "Teaching staff with academic management access"),
    ("Student", "Student with limited read access"),
    ("Parent", "Parent with access to child information"),
    ("Staff", "Administrative staff with operational access"),
]

STUDENT_PARENT_MENU_URLS = [
    "/dashboard",
    "/students",
    "/students/admission",
    "/students/attendance",
    "/students/studenttransport",
    "/students/studentdocuments",
    "/students/studentcertificates",
    "/fee",
    "/fee/my-fees",
    "/fee/my-receipts",
    "/exam",
    "/exam/exams",
    "/exam/marks",
    "/exam/hall-tickets",
    "/exam/results",
]

ROLE_MANAGEMENT_ACTIONS = ["create", "read", "update", "delete", "list"]

ALL_ADMIN = [
    # Academic
    ("academic_years", "create"),
    ("academic_years", "read"),
    ("academic_years", "update"),
    ("academic_years", "delete"),
    ("academic_years", "list"),
    ("classes", "create"),
    ("classes", "read"),
    ("classes", "update"),
    ("classes", "delete"),
    ("classes", "list"),
    ("subjects", "create"),
    ("subjects", "read"),
    ("subjects", "update"),
    ("subjects", "delete"),
    ("subjects", "list"),
    ("subject_categories", "create"),
    ("subject_categories", "read"),
    ("subject_categories", "update"),
    ("subject_categories", "delete"),
    ("subject_categories", "list"),
    ("class_subject_mappings", "create"),
    ("class_subject_mappings", "read"),
    ("class_subject_mappings", "update"),
    ("class_subject_mappings", "delete"),
    ("class_subject_mappings", "list"),
    # Exam
    ("exams", "create"),
    ("exams", "read"),
    ("exams", "update"),
    ("exams", "delete"),
    ("exams", "list"),
    ("exam_marks", "create"),
    ("exam_marks", "read"),
    ("exam_marks", "list"),
    # Fee
    ("fee_categories", "create"),
    ("fee_categories", "read"),
    ("fee_categories", "update"),
    ("fee_categories", "delete"),
    ("fee_categories", "list"),
    ("fee_types", "create"),
    ("fee_types", "read"),
    ("fee_types", "update"),
    ("fee_types", "delete"),
    ("fee_types", "list"),
    ("fee_terms", "create"),
    ("fee_terms", "read"),
    ("fee_terms", "update"),
    ("fee_terms", "delete"),
    ("fee_terms", "list"),
    ("fee_class_mappings", "create"),
    ("fee_class_mappings", "read"),
    ("fee_class_mappings", "update"),
    ("fee_class_mappings", "delete"),
    ("fee_class_mappings", "list"),
    ("fee_class_mapping_term_amounts", "create"),
    ("fee_class_mapping_term_amounts", "read"),
    ("fee_class_mapping_term_amounts", "update"),
    ("fee_class_mapping_term_amounts", "delete"),
    ("fee_class_mapping_term_amounts", "list"),
    ("fee_student_mappings", "create"),
    ("fee_student_mappings", "read"),
    ("fee_student_mappings", "update"),
    ("fee_student_mappings", "delete"),
    ("fee_student_mappings", "list"),
    ("fee_transactions", "create"),
    ("fee_transactions", "read"),
    ("fee_transactions", "update"),
    ("fee_transactions", "list"),
    ("fee_receipts", "create"),
    ("fee_receipts", "read"),
    ("fee_receipts", "update"),
    ("fee_receipts", "list"),
    ("fee_refunds", "create"),
    ("fee_refunds", "read"),
    ("fee_refunds", "list"),
    ("fee_refunds", "approve"),
    ("fee_refunds", "process"),
    # Students
    ("students", "list"),
    ("student_admissions", "create"),
    ("student_admissions", "read"),
    ("student_admissions", "update"),
    ("student_admissions", "delete"),
    ("student_attendance", "create"),
    ("student_attendance", "read"),
    ("student_attendance", "update"),
    ("student_attendance", "delete"),
    ("student_attendance", "list"),
    ("student_certificates", "create"),
    ("student_certificates", "read"),
    ("student_certificates", "update"),
    ("student_certificates", "delete"),
    ("student_certificates", "list"),
    ("student_documents", "create"),
    ("student_documents", "read"),
    ("student_documents", "update"),
    ("student_documents", "delete"),
    ("student_documents", "list"),
    ("student_transport", "create"),
    ("student_transport", "read"),
    ("student_transport", "update"),
    ("student_transport", "delete"),
    ("student_transport", "list"),
    # Masters / Staff
    ("staff", "create"),
    ("staff", "read"),
    ("staff", "update"),
    ("staff", "delete"),
    ("staff", "list"),
    ("parent_management", "create"),
    ("parent_management", "read"),
    ("parent_management", "update"),
    ("parent_management", "delete"),
    ("parent_management", "list"),
    ("designations", "create"),
    ("designations", "read"),
    ("designations", "update"),
    ("designations", "delete"),
    ("designations", "list"),
    ("locations", "create"),
    ("locations", "read"),
    ("locations", "update"),
    ("locations", "delete"),
    ("locations", "list"),
    ("castes", "create"),
    ("castes", "read"),
    ("castes", "update"),
    ("castes", "delete"),
    ("castes", "list"),
    ("certificate_types", "create"),
    ("certificate_types", "read"),
    ("certificate_types", "update"),
    ("certificate_types", "delete"),
    ("certificate_types", "list"),
    ("holiday_management", "create"),
    ("holiday_management", "read"),
    ("holiday_management", "update"),
    ("holiday_management", "delete"),
    ("holiday_management", "list"),
    # Transport
    ("routes", "create"),
    ("routes", "read"),
    ("routes", "update"),
    ("routes", "delete"),
    ("routes", "list"),
    ("route_types", "create"),
    ("route_types", "read"),
    ("route_types", "update"),
    ("route_types", "delete"),
    ("route_types", "list"),
    ("route_stops", "create"),
    ("route_stops", "read"),
    ("route_stops", "update"),
    ("route_stops", "delete"),
    ("route_stops", "list"),
    ("vehicles", "create"),
    ("vehicles", "read"),
    ("vehicles", "update"),
    ("vehicles", "delete"),
    ("vehicles", "list"),
    ("transport_trips", "create"),
    ("transport_trips", "read"),
    ("transport_trips", "update"),
    ("transport_trips", "delete"),
    ("transport_trips", "list"),
    ("trip_types", "create"),
    ("trip_types", "read"),
    ("trip_types", "update"),
    ("trip_types", "delete"),
    ("trip_types", "list"),
    # Expenses
    ("expense_types", "create"),
    ("expense_types", "read"),
    ("expense_types", "update"),
    ("expense_types", "delete"),
    ("expense_types", "list"),
    ("expense_categories", "create"),
    ("expense_categories", "read"),
    ("expense_categories", "update"),
    ("expense_categories", "delete"),
    ("expense_categories", "list"),
    ("expense_departments", "create"),
    ("expense_departments", "read"),
    ("expense_departments", "update"),
    ("expense_departments", "delete"),
    ("expense_departments", "list"),
    ("expense_settings", "create"),
    ("expense_settings", "read"),
    ("expense_settings", "update"),
    ("expense_settings", "delete"),
    ("expense_settings", "list"),
    ("expense_transactions", "create"),
    ("expense_transactions", "read"),
    ("expense_transactions", "update"),
    ("expense_transactions", "list"),
    ("expense_transactions", "approve"),
    ("expense_attachments", "create"),
    ("expense_attachments", "read"),
    ("expense_attachments", "update"),
    ("expense_attachments", "delete"),
    ("expense_audit_logs", "read"),
    ("expense_audit_logs", "delete"),
    # Reports
    ("fee_reports", "read"),
    ("fee_reports", "export"),
    ("financial_reports", "read"),
    ("financial_reports", "export"),
    ("student_reports", "read"),
    ("student_reports", "export"),
    ("staff_reports", "read"),
    ("staff_reports", "export"),
    ("attendance_reports", "read"),
    ("attendance_reports", "export"),
    ("reports", "read"),
    # Auth / admin
    ("role_management", "create"),
    ("role_management", "read"),
    ("role_management", "update"),
    ("role_management", "delete"),
    ("role_management", "list"),
    ("permission_management", "create"),
    ("permission_management", "list"),
    ("resource_permission_management", "create"),
    ("resource_permission_management", "read"),
    ("resource_permission_management", "update"),
    ("resource_permission_management", "delete"),
    ("resource_permission_management", "list"),
    ("user_management", "read"),
    ("user_management", "update"),
    ("user_management", "list"),
    ("menu_management", "create"),
    ("menu_management", "list"),
    ("organizations", "create"),
    ("organizations", "read"),
    ("organizations", "update"),
    ("organizations", "delete"),
    ("organizations", "list"),
    ("fee_collection", "create"),
    ("fee_collection", "read"),
    ("fee_collection", "list"),
    ("fee_concessions", "create"),
    ("fee_concessions", "read"),
    ("fee_concessions", "update"),
    ("fee_concessions", "delete"),
    ("fee_concessions", "list"),
    ("fee_old", "create"),
    ("fee_old", "read"),
    ("fee_old", "update"),
    ("fee_old", "delete"),
    ("fee_old", "list"),
    ("transport_pricing", "create"),
    ("transport_pricing", "read"),
    ("transport_pricing", "update"),
    ("transport_pricing", "delete"),
    ("transport_pricing", "list"),
    ("staff_attendance", "create"),
    ("staff_attendance", "read"),
    ("staff_attendance", "update"),
    ("staff_attendance", "delete"),
    ("staff_attendance", "list"),
    ("timetable_management", "create"),
    ("timetable_management", "read"),
    ("timetable_management", "update"),
    ("timetable_management", "delete"),
    ("timetable_management", "list"),
    ("school_settings", "read"),
    ("school_settings", "update"),
    ("communications", "create"),
    ("communications", "read"),
    ("communications", "update"),
    ("communications", "list"),
    ("expense_reports", "read"),
    ("expense_reports", "list"),
    ("expense_reports", "export"),
    ("issuable_certificates", "create"),
    ("issuable_certificates", "read"),
    ("issuable_certificates", "update"),
    ("issuable_certificates", "delete"),
    ("issuable_certificates", "list"),
    ("sections", "create"),
    ("student_admissions", "list"),
    ("monitoring", "read"),
    ("monitoring", "admin"),
]

READ_ONLY_ACADEMIC = [
    ("academic_years", "read"),
    ("academic_years", "list"),
    ("classes", "read"),
    ("classes", "list"),
    ("sections", "read"),
    ("sections", "list"),
    ("subjects", "read"),
    ("subjects", "list"),
    ("subject_categories", "read"),
    ("subject_categories", "list"),
    ("class_subject_mappings", "read"),
    ("class_subject_mappings", "list"),
    ("holiday_management", "read"),
    ("holiday_management", "list"),
    ("locations", "read"),
    ("locations", "list"),
    ("castes", "read"),
    ("castes", "list"),
    ("certificate_types", "read"),
    ("certificate_types", "list"),
    ("designations", "read"),
    ("designations", "list"),
]

ROLE_PERMISSIONS = {
    "Admin": ALL_ADMIN,
    "Teacher": READ_ONLY_ACADEMIC
    + [
        # Exam
        ("exams", "read"),
        ("exams", "list"),
        ("exam_marks", "create"),
        ("exam_marks", "read"),
        ("exam_marks", "list"),
        # Students
        ("students", "list"),
        ("student_admissions", "read"),
        ("student_admissions", "list"),
        ("student_attendance", "create"),
        ("student_attendance", "read"),
        ("student_attendance", "update"),
        ("student_attendance", "list"),
        ("student_certificates", "read"),
        ("student_certificates", "list"),
        ("student_documents", "read"),
        ("student_documents", "list"),
        # Transport (read-only)
        ("routes", "read"),
        ("routes", "list"),
        ("route_stops", "read"),
        ("route_stops", "list"),
        ("vehicles", "read"),
        ("vehicles", "list"),
        ("transport_trips", "read"),
        ("transport_trips", "list"),
        ("route_types", "read"),
        ("route_types", "list"),
        ("trip_types", "read"),
        ("trip_types", "list"),
        # Reports
        ("student_reports", "read"),
        ("student_reports", "export"),
        ("attendance_reports", "read"),
        ("attendance_reports", "export"),
        ("reports", "read"),
    ],
    "Student": [
        # Own profile
        ("profile", "read_own"),
        ("profile", "update_own"),
        # Reference data (read-only, not personal)
        ("academic_years", "read"),
        ("academic_years", "list"),
        ("classes", "read"),
        ("classes", "list"),
        ("subjects", "read"),
        ("subjects", "list"),
        ("certificate_types", "read"),
        ("certificate_types", "list"),
        # Exam (own results & hall tickets)
        ("exams", "read"),
        ("exams", "list"),
        ("exam_marks", "read_own"),
        ("exam_marks", "list_own"),
        ("exam_results", "read_own"),
        ("exam_results", "list_own"),
        ("exam_hall_tickets", "read_own"),
        ("exam_hall_tickets", "list_own"),
        # Own student data only
        ("student_admissions", "read_own"),
        ("student_admissions", "list_own"),
        ("student_attendance", "read_own"),
        ("student_attendance", "list_own"),
        ("student_certificates", "read_own"),
        ("student_certificates", "list_own"),
        ("student_documents", "read_own"),
        ("student_documents", "list_own"),
        ("student_transport", "read_own"),
        # Fee (own only)
        ("fee_receipts", "read_own"),
        ("fee_receipts", "list_own"),
        ("fee_transactions", "read_own"),
        ("fee_transactions", "list_own"),
    ],
    "Parent": [
        # Reference data (needed to display class/section names)
        ("academic_years", "read"),
        ("academic_years", "list"),
        ("classes", "read"),
        ("classes", "list"),
        ("subjects", "read"),
        ("subjects", "list"),
        # Children's details (related = only linked children)
        ("student_admissions", "read_related"),
        ("student_admissions", "list_related"),
        ("student_attendance", "read_related"),
        ("student_attendance", "list_related"),
        ("student_certificates", "read_related"),
        ("student_certificates", "list_related"),
        ("student_documents", "read_related"),
        ("student_documents", "list_related"),
        ("student_transport", "read_related"),
        # Marks & Exam results (children only)
        ("exams", "read"),
        ("exams", "list"),
        ("exam_marks", "read_related"),
        ("exam_marks", "list_related"),
        # Hall tickets (children only)
        ("exam_hall_tickets", "read_related"),
        ("exam_hall_tickets", "list_related"),
        # Fee (children only)
        ("fee_transactions", "read_related"),
        ("fee_collection", "read_related"),
        ("fee_receipts", "read_related"),
    ],
    "Staff": READ_ONLY_ACADEMIC
    + [
        # Exam (read-only)
        ("exams", "read"),
        ("exams", "list"),
        ("exam_marks", "read"),
        ("exam_marks", "list"),
        # Students (create/update, no delete)
        ("students", "list"),
        ("student_admissions", "create"),
        ("student_admissions", "read"),
        ("student_admissions", "update"),
        ("student_admissions", "list"),
        ("student_attendance", "create"),
        ("student_attendance", "read"),
        ("student_attendance", "update"),
        ("student_attendance", "list"),
        ("student_certificates", "create"),
        ("student_certificates", "read"),
        ("student_certificates", "update"),
        ("student_certificates", "list"),
        ("student_documents", "create"),
        ("student_documents", "read"),
        ("student_documents", "update"),
        ("student_documents", "list"),
        ("student_transport", "create"),
        ("student_transport", "read"),
        ("student_transport", "update"),
        ("student_transport", "list"),
        # Fee (full ops except delete/approve)
        ("fee_categories", "read"),
        ("fee_categories", "list"),
        ("fee_types", "read"),
        ("fee_types", "list"),
        ("fee_terms", "read"),
        ("fee_terms", "list"),
        ("fee_class_mappings", "read"),
        ("fee_class_mappings", "list"),
        ("fee_class_mapping_term_amounts", "read"),
        ("fee_class_mapping_term_amounts", "list"),
        ("fee_student_mappings", "create"),
        ("fee_student_mappings", "read"),
        ("fee_student_mappings", "update"),
        ("fee_student_mappings", "list"),
        ("fee_transactions", "create"),
        ("fee_transactions", "read"),
        ("fee_transactions", "update"),
        ("fee_transactions", "list"),
        ("fee_receipts", "create"),
        ("fee_receipts", "read"),
        ("fee_receipts", "list"),
        ("fee_refunds", "create"),
        ("fee_refunds", "read"),
        ("fee_refunds", "list"),
        # Masters
        ("staff", "read"),
        ("staff", "list"),
        ("parent_management", "create"),
        ("parent_management", "read"),
        ("parent_management", "update"),
        ("parent_management", "list"),
        # Transport
        ("routes", "read"),
        ("routes", "list"),
        ("route_types", "read"),
        ("route_types", "list"),
        ("route_stops", "read"),
        ("route_stops", "list"),
        ("vehicles", "read"),
        ("vehicles", "list"),
        ("transport_trips", "create"),
        ("transport_trips", "read"),
        ("transport_trips", "update"),
        ("transport_trips", "list"),
        ("trip_types", "read"),
        ("trip_types", "list"),
        # Expenses (create & read, not approve/delete)
        ("expense_types", "read"),
        ("expense_types", "list"),
        ("expense_categories", "read"),
        ("expense_categories", "list"),
        ("expense_departments", "read"),
        ("expense_departments", "list"),
        ("expense_transactions", "create"),
        ("expense_transactions", "read"),
        ("expense_transactions", "list"),
        ("expense_attachments", "create"),
        ("expense_attachments", "read"),
        # Reports
        ("fee_reports", "read"),
        ("fee_reports", "export"),
        ("student_reports", "read"),
        ("student_reports", "export"),
        ("attendance_reports", "read"),
        ("attendance_reports", "export"),
        ("staff_reports", "read"),
        ("reports", "read"),
    ],
}
