"""add_fee_transaction_tables_phase_1

Revision ID: 08bbd1b72f43
Revises: a816ac6438cc
Create Date: 2025-09-12 12:11:22.140043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08bbd1b72f43'
down_revision: Union[str, None] = 'a816ac6438cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fee_transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('transaction_number', sa.String(length=50), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('student_admission_num', sa.String(length=50), nullable=False),
    sa.Column('academic_year_id', sa.UUID(), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('payment_method', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('upi_reference', sa.String(length=100), nullable=True),
    sa.Column('upi_app_name', sa.String(length=50), nullable=True),
    sa.Column('cheque_number', sa.String(length=50), nullable=True),
    sa.Column('cheque_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('cheque_bank', sa.String(length=100), nullable=True),
    sa.Column('cheque_status', sa.String(length=20), nullable=True),
    sa.Column('bank_reference', sa.String(length=100), nullable=True),
    sa.Column('bank_name', sa.String(length=100), nullable=True),
    sa.Column('collected_by_user_id', sa.UUID(), nullable=False),
    sa.Column('approved_by_user_id', sa.UUID(), nullable=True),
    sa.Column('receipt_generated', sa.Boolean(), nullable=False),
    sa.Column('receipt_hash', sa.String(length=64), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('transaction_date', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_fee_trans_academic_year', 'fee_transactions', ['academic_year_id', 'transaction_date'], unique=False)
    op.create_index('idx_fee_trans_status_method', 'fee_transactions', ['status', 'payment_method'], unique=False)
    op.create_index('idx_fee_trans_student_date', 'fee_transactions', ['student_id', 'transaction_date'], unique=False)
    op.create_index(op.f('ix_fee_transactions_academic_year_id'), 'fee_transactions', ['academic_year_id'], unique=False)
    op.create_index(op.f('ix_fee_transactions_id'), 'fee_transactions', ['id'], unique=True)
    op.create_index(op.f('ix_fee_transactions_student_admission_num'), 'fee_transactions', ['student_admission_num'], unique=False)
    op.create_index(op.f('ix_fee_transactions_student_id'), 'fee_transactions', ['student_id'], unique=False)
    op.create_index(op.f('ix_fee_transactions_transaction_number'), 'fee_transactions', ['transaction_number'], unique=True)
    op.create_table('fee_receipts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('receipt_number', sa.String(length=50), nullable=False),
    sa.Column('fee_transaction_id', sa.UUID(), nullable=False),
    sa.Column('student_name', sa.String(length=200), nullable=False),
    sa.Column('student_admission_num', sa.String(length=50), nullable=False),
    sa.Column('class_section', sa.String(length=100), nullable=False),
    sa.Column('academic_year', sa.String(length=50), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('pdf_file_path', sa.String(length=500), nullable=True),
    sa.Column('is_reprinted', sa.Boolean(), nullable=False),
    sa.Column('reprint_count', sa.String(), server_default='0', nullable=False),
    sa.Column('generated_by_user_id', sa.UUID(), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('generated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['fee_transaction_id'], ['fee_transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fee_receipts_fee_transaction_id'), 'fee_receipts', ['fee_transaction_id'], unique=False)
    op.create_index(op.f('ix_fee_receipts_id'), 'fee_receipts', ['id'], unique=True)
    op.create_index(op.f('ix_fee_receipts_receipt_number'), 'fee_receipts', ['receipt_number'], unique=True)
    op.create_table('fee_refunds',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('refund_number', sa.String(length=50), nullable=False),
    sa.Column('fee_transaction_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('student_admission_num', sa.String(length=50), nullable=False),
    sa.Column('academic_year_id', sa.UUID(), nullable=False),
    sa.Column('refund_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('refund_reason', sa.String(length=20), nullable=False),
    sa.Column('detailed_reason', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('requested_by_user_id', sa.UUID(), nullable=False),
    sa.Column('approved_by_user_id', sa.UUID(), nullable=True),
    sa.Column('processed_by_user_id', sa.UUID(), nullable=True),
    sa.Column('refund_method', sa.String(length=20), nullable=True),
    sa.Column('refund_reference', sa.String(length=100), nullable=True),
    sa.Column('approval_remarks', sa.Text(), nullable=True),
    sa.Column('processing_remarks', sa.Text(), nullable=True),
    sa.Column('requested_date', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('approved_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('processed_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['fee_transaction_id'], ['fee_transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fee_refunds_fee_transaction_id'), 'fee_refunds', ['fee_transaction_id'], unique=False)
    op.create_index(op.f('ix_fee_refunds_id'), 'fee_refunds', ['id'], unique=True)
    op.create_index(op.f('ix_fee_refunds_refund_number'), 'fee_refunds', ['refund_number'], unique=True)
    op.create_index(op.f('ix_fee_refunds_student_id'), 'fee_refunds', ['student_id'], unique=False)
    op.create_table('fee_transaction_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('fee_transaction_id', sa.UUID(), nullable=False),
    sa.Column('fee_type_id', sa.UUID(), nullable=False),
    sa.Column('fee_term_id', sa.UUID(), nullable=False),
    sa.Column('amount_due', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('amount_paid', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['fee_transaction_id'], ['fee_transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_fee_trans_item_fee_type', 'fee_transaction_items', ['fee_type_id', 'fee_term_id'], unique=False)
    op.create_index('idx_fee_trans_item_transaction', 'fee_transaction_items', ['fee_transaction_id'], unique=False)
    op.create_index(op.f('ix_fee_transaction_items_fee_term_id'), 'fee_transaction_items', ['fee_term_id'], unique=False)
    op.create_index(op.f('ix_fee_transaction_items_fee_transaction_id'), 'fee_transaction_items', ['fee_transaction_id'], unique=False)
    op.create_index(op.f('ix_fee_transaction_items_fee_type_id'), 'fee_transaction_items', ['fee_type_id'], unique=False)
    op.create_index(op.f('ix_fee_transaction_items_id'), 'fee_transaction_items', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fee_transaction_items_id'), table_name='fee_transaction_items')
    op.drop_index(op.f('ix_fee_transaction_items_fee_type_id'), table_name='fee_transaction_items')
    op.drop_index(op.f('ix_fee_transaction_items_fee_transaction_id'), table_name='fee_transaction_items')
    op.drop_index(op.f('ix_fee_transaction_items_fee_term_id'), table_name='fee_transaction_items')
    op.drop_index('idx_fee_trans_item_transaction', table_name='fee_transaction_items')
    op.drop_index('idx_fee_trans_item_fee_type', table_name='fee_transaction_items')
    op.drop_table('fee_transaction_items')
    op.drop_index(op.f('ix_fee_refunds_student_id'), table_name='fee_refunds')
    op.drop_index(op.f('ix_fee_refunds_refund_number'), table_name='fee_refunds')
    op.drop_index(op.f('ix_fee_refunds_id'), table_name='fee_refunds')
    op.drop_index(op.f('ix_fee_refunds_fee_transaction_id'), table_name='fee_refunds')
    op.drop_table('fee_refunds')
    op.drop_index(op.f('ix_fee_receipts_receipt_number'), table_name='fee_receipts')
    op.drop_index(op.f('ix_fee_receipts_id'), table_name='fee_receipts')
    op.drop_index(op.f('ix_fee_receipts_fee_transaction_id'), table_name='fee_receipts')
    op.drop_table('fee_receipts')
    op.drop_index(op.f('ix_fee_transactions_transaction_number'), table_name='fee_transactions')
    op.drop_index(op.f('ix_fee_transactions_student_id'), table_name='fee_transactions')
    op.drop_index(op.f('ix_fee_transactions_student_admission_num'), table_name='fee_transactions')
    op.drop_index(op.f('ix_fee_transactions_id'), table_name='fee_transactions')
    op.drop_index(op.f('ix_fee_transactions_academic_year_id'), table_name='fee_transactions')
    op.drop_index('idx_fee_trans_student_date', table_name='fee_transactions')
    op.drop_index('idx_fee_trans_status_method', table_name='fee_transactions')
    op.drop_index('idx_fee_trans_academic_year', table_name='fee_transactions')
    op.drop_table('fee_transactions')
    # ### end Alembic commands ###
