"""Update staff tables 8

Revision ID: 1b8e0c605c71
Revises: 3aca47a14c15
Create Date: 2025-07-17 18:04:48.691852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1b8e0c605c71'
down_revision: Union[str, None] = '3aca47a14c15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('staff_attendance', 'status',
               existing_type=postgresql.ENUM('present', 'absent', 'leave', 'half_day', name='attendancestatusenum'),
               type_=sa.String(length=10),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('staff_attendance', 'status',
               existing_type=sa.String(length=10),
               type_=postgresql.ENUM('present', 'absent', 'leave', 'half_day', name='attendancestatusenum'),
               existing_nullable=False)
    # ### end Alembic commands ###
