"""remove academic_year_id to classes

Revision ID: 2c8021b74775
Revises: 6b1dc0799b32
Create Date: 2025-06-25 00:24:52.303277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c8021b74775'
down_revision: Union[str, None] = '6b1dc0799b32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_classes_academic_year_id'), table_name='classes')
    op.drop_constraint(op.f('classes_academic_year_id_fkey'), 'classes', type_='foreignkey')
    op.drop_column('classes', 'academic_year_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('classes', sa.Column('academic_year_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('classes_academic_year_id_fkey'), 'classes', 'academic_years', ['academic_year_id'], ['id'])
    op.create_index(op.f('ix_classes_academic_year_id'), 'classes', ['academic_year_id'], unique=False)
    # ### end Alembic commands ###
