"""Add user_id to students

Revision ID: 47d338492a6b
Revises: bf9c19e4cdb7
Create Date: 2025-07-17 01:19:10.776175

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47d338492a6b'
down_revision: Union[str, None] = 'bf9c19e4cdb7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parents', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'parents', ['user_id'])
    op.create_foreign_key(None, 'parents', 'users', ['user_id'], ['id'])
    op.add_column('staff', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'staff', ['user_id'])
    op.create_foreign_key(None, 'staff', 'users', ['user_id'], ['id'])
    op.add_column('students', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'students', ['user_id'])
    op.create_foreign_key(None, 'students', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'students', type_='foreignkey')
    op.drop_constraint(None, 'students', type_='unique')
    op.drop_column('students', 'user_id')
    op.drop_constraint(None, 'staff', type_='foreignkey')
    op.drop_constraint(None, 'staff', type_='unique')
    op.drop_column('staff', 'user_id')
    op.drop_constraint(None, 'parents', type_='foreignkey')
    op.drop_constraint(None, 'parents', type_='unique')
    op.drop_column('parents', 'user_id')
    # ### end Alembic commands ###
