"""add column isactive

Revision ID: 4fd1ec6920e2
Revises: c9bb78abcbe6
Create Date: 2025-07-01 21:50:39.945632

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4fd1ec6920e2'
down_revision: Union[str, None] = 'c9bb78abcbe6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_trips', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student_trips', 'is_active')
    # ### end Alembic commands ###
