"""Add fee_categories, fee_terms, and fee_term_dates tables (v2)

Revision ID: 5262d183c37e
Revises: 71ebafea9d5d
Create Date: 2025-08-28 13:03:17.721554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5262d183c37e'
down_revision: Union[str, None] = '71ebafea9d5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fee_categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('category_name', sa.String(length=100), nullable=False),
    sa.Column('category_status', sa.String(length=20), nullable=False),
    sa.Column('academic_year_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category_name', 'academic_year_id', name='uq_category_name_academic_year')
    )
    op.create_index(op.f('ix_fee_categories_id'), 'fee_categories', ['id'], unique=True)
    op.create_table('fee_terms',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('term_name', sa.String(length=50), nullable=False),
    sa.Column('term_status', sa.String(length=20), nullable=False),
    sa.Column('number_of_terms', sa.Integer(), nullable=False),
    sa.Column('academic_year_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fee_terms_id'), 'fee_terms', ['id'], unique=True)
    op.create_table('fee_term_dates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('term_id', sa.UUID(), nullable=False),
    sa.Column('fee_term_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['term_id'], ['fee_terms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fee_term_dates_id'), 'fee_term_dates', ['id'], unique=False)
    op.create_index(op.f('ix_fee_term_dates_term_id'), 'fee_term_dates', ['term_id'], unique=False)
    op.create_table('fee_types',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('type_name', sa.String(length=100), nullable=False),
    sa.Column('fee_category_id', sa.UUID(), nullable=False),
    sa.Column('fee_status', sa.String(length=20), nullable=False),
    sa.Column('fee_term_id', sa.UUID(), nullable=False),
    sa.Column('academic_year_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.id'], ),
    sa.ForeignKeyConstraint(['fee_category_id'], ['fee_categories.id'], ),
    sa.ForeignKeyConstraint(['fee_term_id'], ['fee_terms.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('type_name', 'fee_category_id', name='uq_type_name_fee_category')
    )
    op.create_index(op.f('ix_fee_types_id'), 'fee_types', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fee_types_id'), table_name='fee_types')
    op.drop_table('fee_types')
    op.drop_index(op.f('ix_fee_term_dates_term_id'), table_name='fee_term_dates')
    op.drop_index(op.f('ix_fee_term_dates_id'), table_name='fee_term_dates')
    op.drop_table('fee_term_dates')
    op.drop_index(op.f('ix_fee_terms_id'), table_name='fee_terms')
    op.drop_table('fee_terms')
    op.drop_index(op.f('ix_fee_categories_id'), table_name='fee_categories')
    op.drop_table('fee_categories')
    # ### end Alembic commands ###
