"""Update staff tables

Revision ID: 53ad8ae76ad8
Revises: 47d338492a6b
Create Date: 2025-07-17 14:00:10.700161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53ad8ae76ad8'
down_revision: Union[str, None] = '47d338492a6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('staff', sa.Column('role', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'staff', 'roles', ['role'], ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'staff', type_='foreignkey')
    op.drop_column('staff', 'role')
    # ### end Alembic commands ###
