"""Modify routes table

Revision ID: 6632b8389a75
Revises: 1f9c1e15a8d2
Create Date: 2025-07-31 00:00:13.286548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6632b8389a75'
down_revision: Union[str, None] = '1f9c1e15a8d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('route_stops', sa.Column('reaching_time', sa.Time(), nullable=True))
    op.drop_column('route_stops', 'time')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('route_stops', sa.Column('time', postgresql.TIME(), autoincrement=False, nullable=True))
    op.drop_column('route_stops', 'reaching_time')
    # ### end Alembic commands ###
