"""Add fee_categories, fee_terms, and fee_term_dates tables

Revision ID: 71ebafea9d5d
Revises: a7b83ff63a13
Create Date: 2025-08-28 13:01:23.234153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71ebafea9d5d'
down_revision: Union[str, None] = 'a7b83ff63a13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('certificate_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_certificate_types_id'), 'certificate_types', ['id'], unique=False)
    op.create_table('designations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_index(op.f('ix_designations_id'), 'designations', ['id'], unique=False)
    op.create_table('routes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('route_name', sa.String(), nullable=False),
    sa.Column('starting_stop', sa.String(), nullable=False),
    sa.Column('ending_stop', sa.String(), nullable=False),
    sa.Column('number_of_stops', sa.Integer(), nullable=True),
    sa.Column('route_type', sa.String(), nullable=True),
    sa.Column('trip_type', sa.String(), nullable=True),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_routes_id'), 'routes', ['id'], unique=False)
    op.create_table('subject_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_subject_categories_id'), 'subject_categories', ['id'], unique=False)
    op.create_table('vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('registration_number', sa.String(), nullable=True),
    sa.Column('vehicle_type', sa.String(), nullable=True),
    sa.Column('last_inspected_date', sa.Date(), nullable=True),
    sa.Column('pollution_renewal_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('registration_number')
    )
    op.create_index(op.f('ix_vehicles_id'), 'vehicles', ['id'], unique=False)
    op.create_table('route_stops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('route_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('reaching_time', sa.Time(), nullable=True),
    sa.Column('fees', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_route_stops_id'), 'route_stops', ['id'], unique=False)
    op.create_table('parents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=15), nullable=True),
    sa.Column('occupation', sa.String(length=100), nullable=True),
    sa.Column('aadhar_number', sa.String(length=12), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('relation_to_student', sa.String(length=20), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_parents_id'), 'parents', ['id'], unique=False)
    op.create_table('staff',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=15), nullable=True),
    sa.Column('gender', sa.Enum('male', 'female', 'other', name='genderenum'), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('joining_date', sa.Date(), nullable=False),
    sa.Column('qualification', sa.String(length=100), nullable=True),
    sa.Column('experience_years', sa.Integer(), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('designation_id', sa.Integer(), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['designation_id'], ['designations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_staff_id'), 'staff', ['id'], unique=False)
    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('is_primary', sa.String(length=20), nullable=True),
    sa.Column('aadhar_number', sa.String(length=12), nullable=True),
    sa.Column('apaar_number', sa.String(length=12), nullable=True),
    sa.Column('caste', sa.String(length=100), nullable=True),
    sa.Column('sub_caste', sa.String(length=100), nullable=True),
    sa.Column('community', sa.String(length=100), nullable=True),
    sa.Column('nationality', sa.String(length=100), nullable=True),
    sa.Column('mother_tongue', sa.String(length=100), nullable=True),
    sa.Column('identification_marks', sa.String(length=100), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_students_id'), 'students', ['id'], unique=False)
    op.create_table('trips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('route_id', sa.Integer(), nullable=True),
    sa.Column('driver_id', sa.Integer(), nullable=True),
    sa.Column('trip_number', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trips_id'), 'trips', ['id'], unique=False)
    op.create_table('slot_times',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_slot_times_id'), 'slot_times', ['id'], unique=False)
    op.create_table('staff_attendance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('staff_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('staff_id', 'date', name='uq_staff_date')
    )
    op.create_index(op.f('ix_staff_attendance_id'), 'staff_attendance', ['id'], unique=False)
    op.create_table('student_admissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('admission_date', sa.Date(), nullable=False),
    sa.Column('academic_year_id', sa.Integer(), nullable=True),
    sa.Column('admitted_class_id', sa.Integer(), nullable=True),
    sa.Column('admitted_section_id', sa.Integer(), nullable=True),
    sa.Column('current_class_id', sa.Integer(), nullable=True),
    sa.Column('current_section_id', sa.Integer(), nullable=True),
    sa.Column('address_line1', sa.String(length=255), nullable=True),
    sa.Column('address_line2', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('is_previous_school', sa.Boolean(), nullable=True),
    sa.Column('previous_school_name', sa.String(length=255), nullable=True),
    sa.Column('previous_class', sa.String(length=50), nullable=True),
    sa.Column('previous_school_remark', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.id'], ),
    sa.ForeignKeyConstraint(['admitted_class_id'], ['classes.id'], ),
    sa.ForeignKeyConstraint(['admitted_section_id'], ['sections.id'], ),
    sa.ForeignKeyConstraint(['current_class_id'], ['classes.id'], ),
    sa.ForeignKeyConstraint(['current_section_id'], ['sections.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_admissions_id'), 'student_admissions', ['id'], unique=False)
    op.create_table('student_attendance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_attendance_id'), 'student_attendance', ['id'], unique=False)
    op.create_table('student_certificates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('certificate_type_id', sa.Integer(), nullable=True),
    sa.Column('issue_date', sa.Date(), nullable=True),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.Column('remarks', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['certificate_type_id'], ['certificate_types.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_certificates_id'), 'student_certificates', ['id'], unique=False)
    op.create_table('student_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('document_type', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('upload_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_documents_id'), 'student_documents', ['id'], unique=False)
    op.create_table('student_homework',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('submission_status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_homework_id'), 'student_homework', ['id'], unique=False)
    op.create_table('student_parent_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['parents.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_parent_links_id'), 'student_parent_links', ['id'], unique=False)
    op.create_table('student_transport_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('stop_id', sa.Integer(), nullable=False),
    sa.Column('fee_per_term', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['stop_id'], ['route_stops.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_transport_assignments_id'), 'student_transport_assignments', ['id'], unique=False)
    op.create_table('student_trips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('stop_id', sa.Integer(), nullable=True),
    sa.Column('fee_term_id', sa.Integer(), nullable=True),
    sa.Column('fee_per_term', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['stop_id'], ['route_stops.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_trips_id'), 'student_trips', ['id'], unique=False)
    op.create_table('timetables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('section_id')
    )
    op.create_index(op.f('ix_timetables_id'), 'timetables', ['id'], unique=False)
    op.create_table('timetable_slots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timetable_id', sa.Integer(), nullable=True),
    sa.Column('day', sa.String(), nullable=False),
    sa.Column('slot_time_id', sa.Integer(), nullable=True),
    sa.Column('is_break', sa.Boolean(), nullable=True),
    sa.Column('break_label', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['slot_time_id'], ['slot_times.id'], ),
    sa.ForeignKeyConstraint(['timetable_id'], ['timetables.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_timetable_slots_id'), 'timetable_slots', ['id'], unique=False)
    op.create_table('timetable_subject_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slot_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['slot_id'], ['timetable_slots.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_timetable_subject_options_id'), 'timetable_subject_options', ['id'], unique=False)
    op.add_column('subjects', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'subjects', 'subject_categories', ['category_id'], ['id'])
    op.drop_column('subjects', 'category')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subjects', sa.Column('category', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'subjects', type_='foreignkey')
    op.drop_column('subjects', 'category_id')
    op.drop_index(op.f('ix_timetable_subject_options_id'), table_name='timetable_subject_options')
    op.drop_table('timetable_subject_options')
    op.drop_index(op.f('ix_timetable_slots_id'), table_name='timetable_slots')
    op.drop_table('timetable_slots')
    op.drop_index(op.f('ix_timetables_id'), table_name='timetables')
    op.drop_table('timetables')
    op.drop_index(op.f('ix_student_trips_id'), table_name='student_trips')
    op.drop_table('student_trips')
    op.drop_index(op.f('ix_student_transport_assignments_id'), table_name='student_transport_assignments')
    op.drop_table('student_transport_assignments')
    op.drop_index(op.f('ix_student_parent_links_id'), table_name='student_parent_links')
    op.drop_table('student_parent_links')
    op.drop_index(op.f('ix_student_homework_id'), table_name='student_homework')
    op.drop_table('student_homework')
    op.drop_index(op.f('ix_student_documents_id'), table_name='student_documents')
    op.drop_table('student_documents')
    op.drop_index(op.f('ix_student_certificates_id'), table_name='student_certificates')
    op.drop_table('student_certificates')
    op.drop_index(op.f('ix_student_attendance_id'), table_name='student_attendance')
    op.drop_table('student_attendance')
    op.drop_index(op.f('ix_student_admissions_id'), table_name='student_admissions')
    op.drop_table('student_admissions')
    op.drop_index(op.f('ix_staff_attendance_id'), table_name='staff_attendance')
    op.drop_table('staff_attendance')
    op.drop_index(op.f('ix_slot_times_id'), table_name='slot_times')
    op.drop_table('slot_times')
    op.drop_index(op.f('ix_trips_id'), table_name='trips')
    op.drop_table('trips')
    op.drop_index(op.f('ix_students_id'), table_name='students')
    op.drop_table('students')
    op.drop_index(op.f('ix_staff_id'), table_name='staff')
    op.drop_table('staff')
    op.drop_index(op.f('ix_parents_id'), table_name='parents')
    op.drop_table('parents')
    op.drop_index(op.f('ix_route_stops_id'), table_name='route_stops')
    op.drop_table('route_stops')
    op.drop_index(op.f('ix_vehicles_id'), table_name='vehicles')
    op.drop_table('vehicles')
    op.drop_index(op.f('ix_subject_categories_id'), table_name='subject_categories')
    op.drop_table('subject_categories')
    op.drop_index(op.f('ix_routes_id'), table_name='routes')
    op.drop_table('routes')
    op.drop_index(op.f('ix_designations_id'), table_name='designations')
    op.drop_table('designations')
    op.drop_index(op.f('ix_certificate_types_id'), table_name='certificate_types')
    op.drop_table('certificate_types')
    # ### end Alembic commands ###
