"""Add Timetable table

Revision ID: 949a22e8b190
Revises: a8572594916e
Create Date: 2025-07-27 23:45:55.409099

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '949a22e8b190'
down_revision: Union[str, None] = 'a8572594916e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('timetables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('section_id')
    )
    op.create_index(op.f('ix_timetables_id'), 'timetables', ['id'], unique=False)
    op.add_column('timetable_slots', sa.Column('timetable_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'timetable_slots', 'timetables', ['timetable_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'timetable_slots', type_='foreignkey')
    op.drop_column('timetable_slots', 'timetable_id')
    op.drop_index(op.f('ix_timetables_id'), table_name='timetables')
    op.drop_table('timetables')
    # ### end Alembic commands ###
