"""Modify timetable slots table

Revision ID: a8572594916e
Revises: aa147fb9e239
Create Date: 2025-07-24 00:42:36.942675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8572594916e'
down_revision: Union[str, None] = 'aa147fb9e239'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('timetable_slots_section_id_fkey'), 'timetable_slots', type_='foreignkey')
    op.drop_column('timetable_slots', 'section_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('timetable_slots', sa.Column('section_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('timetable_slots_section_id_fkey'), 'timetable_slots', 'sections', ['section_id'], ['id'])
    # ### end Alembic commands ###
