"""Add timetable slots table 2

Revision ID: aa147fb9e239
Revises: fa77c24b5af3
Create Date: 2025-07-24 00:18:32.407268

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'aa147fb9e239'
down_revision: Union[str, None] = 'fa77c24b5af3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('slot_times',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_slot_times_id'), 'slot_times', ['id'], unique=False)
    op.add_column('timetable_slots', sa.Column('slot_time_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'timetable_slots', 'slot_times', ['slot_time_id'], ['id'])
    op.drop_column('timetable_slots', 'end_time')
    op.drop_column('timetable_slots', 'start_time')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('timetable_slots', sa.Column('start_time', postgresql.TIME(), autoincrement=False, nullable=False))
    op.add_column('timetable_slots', sa.Column('end_time', postgresql.TIME(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'timetable_slots', type_='foreignkey')
    op.drop_column('timetable_slots', 'slot_time_id')
    op.drop_index(op.f('ix_slot_times_id'), table_name='slot_times')
    op.drop_table('slot_times')
    # ### end Alembic commands ###
