"""Add fee type table

Revision ID: add_fee_type_table
Revises: aa147fb9e239
Create Date: 2025-08-28 12:00:00.000000

"""
from typing import Sequence, Union
import uuid

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'add_fee_type_table'
down_revision: Union[str, None] = 'aa147fb9e239'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fee_types',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False, default=uuid.uuid4),
    sa.Column('type_name', sa.String(length=100), nullable=False),
    sa.Column('fee_category_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('fee_status', sa.String(length=20), nullable=False, server_default='active'),
    sa.Column('fee_term_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('academic_year_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False, server_default=sa.func.now()),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False, server_default=sa.func.now()),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.id'], ),
    sa.ForeignKeyConstraint(['fee_category_id'], ['fee_categories.id'], ),
    sa.ForeignKeyConstraint(['fee_term_id'], ['fee_terms.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('type_name', 'fee_category_id', name='uq_type_name_fee_category')
    )
    op.create_index(op.f('ix_fee_types_id'), 'fee_types', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fee_types_id'), table_name='fee_types')
    op.drop_table('fee_types')
    # ### end Alembic commands ###