"""add modified student parent and staff tables

Revision ID: bf9c19e4cdb7
Revises: f5b074e059ac
Create Date: 2025-07-16 20:11:14.680109

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bf9c19e4cdb7'
down_revision: Union[str, None] = 'f5b074e059ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('parents', 'gender',
               existing_type=postgresql.ENUM('Male', 'Female', 'Other', name='gender_enum'),
               type_=sa.String(length=10),
               existing_nullable=True)
    op.alter_column('parents', 'relation_to_student',
               existing_type=postgresql.ENUM('Father', 'Mother', 'Guardian', name='relation_enum'),
               type_=sa.String(length=20),
               nullable=True)
    op.alter_column('student_parent_links', 'student_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('student_parent_links', 'parent_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('student_parent_links_parent_id_fkey'), 'student_parent_links', type_='foreignkey')
    op.drop_constraint(op.f('student_parent_links_student_id_fkey'), 'student_parent_links', type_='foreignkey')
    op.create_foreign_key(None, 'student_parent_links', 'parents', ['parent_id'], ['id'])
    op.create_foreign_key(None, 'student_parent_links', 'students', ['student_id'], ['id'])
    op.add_column('students', sa.Column('is_primary', sa.String(length=20), nullable=True))
    op.alter_column('students', 'first_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('students', 'last_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('students', 'gender',
               existing_type=postgresql.ENUM('Male', 'Female', 'Other', name='gender_enum'),
               type_=sa.String(length=10),
               existing_nullable=True)
    op.alter_column('students', 'nationality',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('students', 'mother_tongue',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.drop_constraint(op.f('students_admission_number_key'), 'students', type_='unique')
    op.drop_constraint(op.f('students_user_id_key'), 'students', type_='unique')
    op.drop_constraint(op.f('students_section_id_fkey'), 'students', type_='foreignkey')
    op.drop_constraint(op.f('students_user_id_fkey'), 'students', type_='foreignkey')
    op.drop_constraint(op.f('students_class_id_fkey'), 'students', type_='foreignkey')
    op.drop_column('students', 'admission_number')
    op.drop_column('students', 'updated_at')
    op.drop_column('students', 'user_id')
    op.drop_column('students', 'class_id')
    op.drop_column('students', 'created_at')
    op.drop_column('students', 'section_id')
    op.drop_column('students', 'student_photo')
    op.drop_column('students', 'is_active')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('students', sa.Column('student_photo', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('students', sa.Column('section_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('students', sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('students', sa.Column('class_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('students', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('students', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('students', sa.Column('admission_number', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('students_class_id_fkey'), 'students', 'classes', ['class_id'], ['id'])
    op.create_foreign_key(op.f('students_user_id_fkey'), 'students', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('students_section_id_fkey'), 'students', 'sections', ['section_id'], ['id'])
    op.create_unique_constraint(op.f('students_user_id_key'), 'students', ['user_id'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('students_admission_number_key'), 'students', ['admission_number'], postgresql_nulls_not_distinct=False)
    op.alter_column('students', 'mother_tongue',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('students', 'nationality',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('students', 'gender',
               existing_type=sa.String(length=10),
               type_=postgresql.ENUM('Male', 'Female', 'Other', name='gender_enum'),
               existing_nullable=True)
    op.alter_column('students', 'last_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('students', 'first_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_column('students', 'is_primary')
    op.drop_constraint(None, 'student_parent_links', type_='foreignkey')
    op.drop_constraint(None, 'student_parent_links', type_='foreignkey')
    op.create_foreign_key(op.f('student_parent_links_student_id_fkey'), 'student_parent_links', 'students', ['student_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('student_parent_links_parent_id_fkey'), 'student_parent_links', 'parents', ['parent_id'], ['id'], ondelete='CASCADE')
    op.alter_column('student_parent_links', 'parent_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('student_parent_links', 'student_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('parents', 'relation_to_student',
               existing_type=sa.String(length=20),
               type_=postgresql.ENUM('Father', 'Mother', 'Guardian', name='relation_enum'),
               nullable=False)
    op.alter_column('parents', 'gender',
               existing_type=sa.String(length=10),
               type_=postgresql.ENUM('Male', 'Female', 'Other', name='gender_enum'),
               existing_nullable=True)
    # ### end Alembic commands ###
