// src/types/certificates/issuable.ts
// Types for Issuable Certificates (generated by school)
// Matches backend schemas: IssuableCertificateTemplateRead, GeneratedCertificateRead

export interface IssuableCertificateTemplate {
  id: string;
  name: string;
  html_template: string; // HTML with {{placeholders}}
  color_theme: "blue" | "green" | "red" | "orange";
  variables_used: string | null; // comma-separated string from backend e.g. "student_name,father_name,..."
  is_active: string; // backend stores as string "True" / "False"
  created_at: string;
  updated_at: string;
}

export interface CreateTemplateRequest {
  name: string;
  html_template: string;
  color_theme: "blue" | "green" | "red" | "orange";
}

export interface UpdateTemplateRequest {
  name?: string;
  html_template?: string;
  color_theme?: "blue" | "green" | "red" | "orange";
  is_active?: string;
}

// Matches backend GeneratedCertificateRead
export interface IssuedCertificate {
  id: string;
  student_id: string;
  template_id: string;
  html_content: string;
  issued_date: string;
  issued_by: string; // user UUID
  remarks?: string;
  is_active: string; // "True" / "False"
  created_at: string;
  updated_at: string;
}

export interface GenerateCertificateRequest {
  student_id: string;
  template_id: string;
  edited_html: string;
  remarks?: string;
}

// Matches backend GenerateCertificateResponse (wraps GeneratedCertificateRead)
export interface GenerateCertificateResponse {
  id: string;
  status: string;
  message: string;
  download_url?: string | null;
}

export interface StudentDataForCertificate {
  student_id: string;
  name: string;
  admission_number: string;
  father_name?: string;
  mother_name?: string;
  dob?: string;
  class?: string;
  section?: string;
  gender?: string;
  academic_year?: string;
  school_name?: string;
}

export interface TemplateFilledData {
  html: string;
  variables: Record<string, string>;
  student_data: StudentDataForCertificate;
}
