// src/types/certificates/issuable.ts
// Types for Issuable Certificates (generated by school)

export interface IssuableCertificateTemplate {
  id: string;
  name: string; // "Bonafide", "Transfer", "Character", etc.
  html_template: string; // HTML with {{placeholders}}
  color_theme: "blue" | "green" | "red" | "orange";
  variables_used: string[]; // ["student_name", "father_name", ...]
  is_active: boolean;
  created_at: string;
  updated_at: string;
}

export interface CreateTemplateRequest {
  name: string;
  html_template: string;
  color_theme: "blue" | "green" | "red" | "orange";
}

export interface UpdateTemplateRequest {
  name?: string;
  html_template?: string;
  color_theme?: "blue" | "green" | "red" | "orange";
  is_active?: boolean;
}

export interface IssuedCertificate {
  id: string;
  student_id: string;
  template_id: string;
  template_name: string;
  html_content: string; // The filled + edited HTML
  pdf_content?: string; // Base64 or file path
  issued_date: string;
  issued_by: string; // user_id
  issued_by_name?: string; // user name
  remarks?: string;
  is_active: boolean;
  created_at: string;
  updated_at: string;
}

export interface GenerateCertificateRequest {
  student_id: string;
  template_id: string;
  edited_html: string; // User can edit before saving
}

export interface GenerateCertificateResponse {
  id: string;
  status: "success" | "error";
  message: string;
  download_url?: string;
  pdf_path?: string;
}

export interface StudentDataForCertificate {
  student_id: string;
  name: string;
  admission_number: string;
  father_name?: string;
  mother_name?: string;
  dob?: string;
  class?: string;
  section?: string;
  gender?: string;
  academic_year?: string;
  school_name?: string;
}

export interface TemplateFilledData {
  html: string;
  variables: Record<string, string>;
  student_data: StudentDataForCertificate;
}
