"""Complete UUID conversion - All phases (1-6)

Revision ID: 086e2d8cc398
Revises: bdaf8eb5c823
Create Date: 2025-09-05 18:38:10.930619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '086e2d8cc398'
down_revision: Union[str, None] = 'bdaf8eb5c823'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    # --- Tenant schema-aware bootstrap (idempotent) ---
    bind = op.get_bind()
    tenant_schema = bind.scalar(sa.text("SELECT current_schema()"))

    # Ensure UUID generator extension exists (for USING gen_random_uuid())
    op.execute('CREATE EXTENSION IF NOT EXISTS "pgcrypto"')

    # Create the enum type in the *tenant* schema if missing
    op.execute(sa.text("""
    DO $$
    BEGIN
        IF NOT EXISTS (
            SELECT 1
            FROM pg_type t
            JOIN pg_namespace n ON n.oid = t.typnamespace
            WHERE t.typname = 'genderenum' AND n.nspname = :schema
        ) THEN
            EXECUTE 'CREATE TYPE "' || :schema || '"."genderenum" AS ENUM (''male'',''female'',''other'')';
        END IF;
    END$$;
""").bindparams(schema=tenant_schema))

    # Reusable enum object that will NOT auto-create the type during table DDL
    gender_enum = postgresql.ENUM(
        'male', 'female', 'other',
        name='genderenum',
        schema=tenant_schema,
        create_type=False,
    )

    # ### commands auto generated by Alembic - adjusted ###

    op.create_table('academic_years',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_index(op.f('ix_academic_years_id'), 'academic_years', ['id'], unique=True)

    op.create_table('designations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_index(op.f('ix_designations_id'), 'designations', ['id'], unique=True)

    op.create_table('menus',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('url', sa.String(length=100), nullable=True),
    sa.Column('level', sa.String(length=2), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['menus.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_menus_id'), 'menus', ['id'], unique=True)

    op.create_table('roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=True)

    op.create_table('routes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('route_name', sa.String(), nullable=False),
    sa.Column('starting_stop', sa.String(), nullable=False),
    sa.Column('ending_stop', sa.String(), nullable=False),
    sa.Column('number_of_stops', sa.Integer(), nullable=True),
    sa.Column('route_type', sa.String(), nullable=True),
    sa.Column('trip_type', sa.String(), nullable=True),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_routes_id'), 'routes', ['id'], unique=True)

    op.create_table('subject_categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_subject_categories_id'), 'subject_categories', ['id'], unique=True)

    op.create_table('vehicles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('registration_number', sa.String(), nullable=True),
    sa.Column('vehicle_type', sa.String(), nullable=True),
    sa.Column('last_inspected_date', sa.Date(), nullable=True),
    sa.Column('pollution_renewal_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('registration_number')
    )
    op.create_index(op.f('ix_vehicles_id'), 'vehicles', ['id'], unique=True)

    op.create_table('classes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('short_code', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('academic_year_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_classes_academic_year_id'), 'classes', ['academic_year_id'], unique=False)
    op.create_index(op.f('ix_classes_id'), 'classes', ['id'], unique=True)

    op.create_table('fee_categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('category_name', sa.String(length=100), nullable=False),
    sa.Column('category_status', sa.String(length=20), nullable=False),
    sa.Column('academic_year_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category_name', 'academic_year_id', name='uq_category_name_academic_year')
    )
    op.create_index(op.f('ix_fee_categories_id'), 'fee_categories', ['id'], unique=True)

    op.create_table('fee_terms',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('term_name', sa.String(length=50), nullable=False),
    sa.Column('term_status', sa.String(length=20), nullable=False),
    sa.Column('number_of_terms', sa.Integer(), nullable=False),
    sa.Column('academic_year_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fee_terms_id'), 'fee_terms', ['id'], unique=True)

    op.create_table('holidays',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('academic_year_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_holidays_academic_year_id'), 'holidays', ['academic_year_id'], unique=False)
    op.create_index(op.f('ix_holidays_id'), 'holidays', ['id'], unique=True)

    op.create_table('role_menu_permissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('menu_id', sa.UUID(), nullable=False),
    sa.Column('can_view', sa.Boolean(), nullable=True),
    sa.Column('can_edit', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['menu_id'], ['menus.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_role_menu_permissions_id'), 'role_menu_permissions', ['id'], unique=True)

    op.create_table('subjects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('short_code', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('academic_year_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['subject_categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_subjects_id'), 'subjects', ['id'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=True)

    op.create_table('class_subject_mappings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('class_id', sa.UUID(), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('academic_year_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.id'], ),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_class_subject_mappings_id'), 'class_subject_mappings', ['id'], unique=True)

    op.create_table('fee_term_dates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('term_id', sa.UUID(), nullable=False),
    sa.Column('fee_term_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['term_id'], ['fee_terms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fee_term_dates_id'), 'fee_term_dates', ['id'], unique=False)
    op.create_index(op.f('ix_fee_term_dates_term_id'), 'fee_term_dates', ['term_id'], unique=False)

    op.create_table('fee_types',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('type_name', sa.String(length=100), nullable=False),
    sa.Column('fee_category_id', sa.UUID(), nullable=False),
    sa.Column('fee_status', sa.String(length=20), nullable=False),
    sa.Column('fee_term_id', sa.UUID(), nullable=False),
    sa.Column('academic_year_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.id'], ),
    sa.ForeignKeyConstraint(['fee_category_id'], ['fee_categories.id'], ),
    sa.ForeignKeyConstraint(['fee_term_id'], ['fee_terms.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('type_name', 'fee_category_id', name='uq_type_name_fee_category')
    )
    op.create_index(op.f('ix_fee_types_id'), 'fee_types', ['id'], unique=True)

    op.create_table('parents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=15), nullable=True),
    sa.Column('occupation', sa.String(length=100), nullable=True),
    sa.Column('aadhar_number', sa.String(length=12), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('relation_to_student', sa.String(length=20), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_parents_id'), 'parents', ['id'], unique=True)

    op.create_table('sections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('class_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_sections_id'), 'sections', ['id'], unique=True)

    op.create_table('staff',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=15), nullable=True),
    sa.Column('gender', gender_enum, nullable=True),  # tenant-scoped enum
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('joining_date', sa.Date(), nullable=False),
    sa.Column('qualification', sa.String(length=100), nullable=True),
    sa.Column('experience_years', sa.Integer(), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('designation_id', sa.UUID(), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['designation_id'], ['designations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_staff_id'), 'staff', ['id'], unique=True)

    op.create_table('students',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('is_primary', sa.String(length=20), nullable=True),
    sa.Column('aadhar_number', sa.String(length=12), nullable=True),
    sa.Column('apaar_number', sa.String(length=12), nullable=True),
    sa.Column('caste', sa.String(length=100), nullable=True),
    sa.Column('sub_caste', sa.String(length=100), nullable=True),
    sa.Column('community', sa.String(length=100), nullable=True),
    sa.Column('nationality', sa.String(length=100), nullable=True),
    sa.Column('mother_tongue', sa.String(length=100), nullable=True),
    sa.Column('identification_marks', sa.String(length=100), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_students_id'), 'students', ['id'], unique=True)

    op.create_table('fee_class_mappings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('class_id', sa.UUID(), nullable=False),
    sa.Column('fee_type_id', sa.UUID(), nullable=False),
    sa.Column('total_fee', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('academic_year_id', sa.UUID(), nullable=False),
    sa.Column('all_by_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.id'], ),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ),
    sa.ForeignKeyConstraint(['fee_type_id'], ['fee_types.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('class_id', 'fee_type_id', 'academic_year_id', name='uq_class_fee_type_academic_year')
    )
    op.create_index(op.f('ix_fee_class_mappings_id'), 'fee_class_mappings', ['id'], unique=True)

    op.create_table('staff_attendance',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('staff_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('staff_id', 'date', name='uq_staff_date')
    )
    op.create_index(op.f('ix_staff_attendance_id'), 'staff_attendance', ['id'], unique=True)

    # ------- Parent PK/type changes BEFORE creating children that reference them -------
    # certificate_types.id INTEGER -> UUID
    op.execute("ALTER TABLE certificate_types ALTER COLUMN id DROP DEFAULT")
    op.execute("""
    DO $$
    DECLARE
        seq_name text := 'certificate_types_id_seq';
        seq_schema text := (SELECT current_schema());
        exists_seq boolean := EXISTS (
            SELECT 1
            FROM pg_class c
            JOIN pg_namespace n ON n.oid = c.relnamespace
            WHERE c.relkind = 'S'
              AND c.relname = seq_name
              AND n.nspname = seq_schema
        );
    BEGIN
        IF exists_seq THEN
            EXECUTE 'DROP SEQUENCE ' || quote_ident(seq_schema) || '.' || quote_ident(seq_name);
        END IF;
    END$$;
""")
    op.alter_column('certificate_types', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.UUID(),
               existing_nullable=False,
               postgresql_using="gen_random_uuid()")
    op.execute("ALTER TABLE certificate_types ALTER COLUMN id SET DEFAULT gen_random_uuid()")
    op.drop_index(op.f('ix_certificate_types_id'), table_name='certificate_types')
    op.create_index(op.f('ix_certificate_types_id'), 'certificate_types', ['id'], unique=True)

    # Convert existing parent tables to UUID before adding child FKs in this revision
    # route_stops
    op.execute("ALTER TABLE route_stops ALTER COLUMN id DROP DEFAULT")
    op.execute("""
        DO $$
        DECLARE
            seq_name text := 'route_stops_id_seq';
            seq_schema text := (SELECT current_schema());
            exists_seq boolean := EXISTS (
                SELECT 1 FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace
                WHERE c.relkind = 'S' AND c.relname = seq_name AND n.nspname = seq_schema
            );
        BEGIN
            IF exists_seq THEN
                EXECUTE 'DROP SEQUENCE ' || quote_ident(seq_schema) || '.' || quote_ident(seq_name);
            END IF;
        END$$;
    """)
    op.alter_column('route_stops', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.UUID(),
               existing_nullable=False,
               postgresql_using="gen_random_uuid()")
    op.execute("ALTER TABLE route_stops ALTER COLUMN id SET DEFAULT gen_random_uuid()")
    op.alter_column('route_stops', 'route_id',
               existing_type=sa.INTEGER(),
               type_=sa.UUID(),
               existing_nullable=True,
               postgresql_using="NULLIF(route_id::text, '')::uuid")
    op.drop_index(op.f('ix_route_stops_id'), table_name='route_stops')
    op.create_index(op.f('ix_route_stops_id'), 'route_stops', ['id'], unique=True)
    op.create_foreign_key(None, 'route_stops', 'routes', ['route_id'], ['id'])

    # slot_times
    op.execute("ALTER TABLE slot_times ALTER COLUMN id DROP DEFAULT")
    op.execute("""
        DO $$
        DECLARE
            seq_name text := 'slot_times_id_seq';
            seq_schema text := (SELECT current_schema());
            exists_seq boolean := EXISTS (
                SELECT 1 FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace
                WHERE c.relkind = 'S' AND c.relname = seq_name AND n.nspname = seq_schema
            );
        BEGIN
            IF exists_seq THEN
                EXECUTE 'DROP SEQUENCE ' || quote_ident(seq_schema) || '.' || quote_ident(seq_name);
            END IF;
        END$$;
    """)
    op.alter_column('slot_times', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.UUID(),
               existing_nullable=False,
               postgresql_using="gen_random_uuid()")
    op.execute("ALTER TABLE slot_times ALTER COLUMN id SET DEFAULT gen_random_uuid()")
    op.alter_column('slot_times', 'section_id',
               existing_type=sa.INTEGER(),
               type_=sa.UUID(),
               existing_nullable=False,
               postgresql_using="NULLIF(section_id::text, '')::uuid")
    op.drop_index(op.f('ix_slot_times_id'), table_name='slot_times')
    op.create_index(op.f('ix_slot_times_id'), 'slot_times', ['id'], unique=True)
    op.create_foreign_key(None, 'slot_times', 'sections', ['section_id'], ['id'])

    # timetables
    op.execute("ALTER TABLE timetables ALTER COLUMN id DROP DEFAULT")
    op.execute("""
        DO $$
        DECLARE
            seq_name text := 'timetables_id_seq';
            seq_schema text := (SELECT current_schema());
            exists_seq boolean := EXISTS (
                SELECT 1 FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace
                WHERE c.relkind = 'S' AND c.relname = seq_name AND n.nspname = seq_schema
            );
        BEGIN
            IF exists_seq THEN
                EXECUTE 'DROP SEQUENCE ' || quote_ident(seq_schema) || '.' || quote_ident(seq_name);
            END IF;
        END$$;
    """)
    op.alter_column('timetables', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.UUID(),
               existing_nullable=False,
               postgresql_using="gen_random_uuid()")
    op.execute("ALTER TABLE timetables ALTER COLUMN id SET DEFAULT gen_random_uuid()")
    op.alter_column('timetables', 'section_id',
               existing_type=sa.INTEGER(),
               type_=sa.UUID(),
               existing_nullable=False,
               postgresql_using="NULLIF(section_id::text, '')::uuid")
    op.drop_index(op.f('ix_timetables_id'), table_name='timetables')
    op.create_index(op.f('ix_timetables_id'), 'timetables', ['id'], unique=True)
    op.create_foreign_key(None, 'timetables', 'sections', ['section_id'], ['id'])

    # trips
    op.execute("ALTER TABLE trips ALTER COLUMN id DROP DEFAULT")
    op.execute("""
        DO $$
        DECLARE
            seq_name text := 'trips_id_seq';
            seq_schema text := (SELECT current_schema());
            exists_seq boolean := EXISTS (
                SELECT 1 FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace
                WHERE c.relkind = 'S' AND c.relname = seq_name AND n.nspname = seq_schema
            );
        BEGIN
            IF exists_seq THEN
                EXECUTE 'DROP SEQUENCE ' || quote_ident(seq_schema) || '.' || quote_ident(seq_name);
            END IF;
        END$$;
    """)
    op.alter_column('trips', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.UUID(),
               existing_nullable=False,
               postgresql_using="gen_random_uuid()")
    op.execute("ALTER TABLE trips ALTER COLUMN id SET DEFAULT gen_random_uuid()")
    op.alter_column('trips', 'vehicle_id',
               existing_type=sa.INTEGER(),
               type_=sa.UUID(),
               existing_nullable=True,
               postgresql_using="NULLIF(vehicle_id::text, '')::uuid")
    op.alter_column('trips', 'route_id',
               existing_type=sa.INTEGER(),
               type_=sa.UUID(),
               existing_nullable=True,
               postgresql_using="NULLIF(route_id::text, '')::uuid")
    op.alter_column('trips', 'driver_id',
               existing_type=sa.INTEGER(),
               type_=sa.UUID(),
               existing_nullable=True,
               postgresql_using="NULLIF(driver_id::text, '')::uuid")
    op.drop_index(op.f('ix_trips_id'), table_name='trips')
    op.create_index(op.f('ix_trips_id'), 'trips', ['id'], unique=True)
    op.create_foreign_key(None, 'trips', 'routes', ['route_id'], ['id'])
    op.create_foreign_key(None, 'trips', 'users', ['driver_id'], ['id'])
    op.create_foreign_key(None, 'trips', 'vehicles', ['vehicle_id'], ['id'])
    # -------------------------------------------------------------------------------

    # Now it is safe to create children that reference the converted parents
    op.create_table('student_admissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('admission_number', sa.String(length=50), nullable=True),
    sa.Column('admission_date', sa.Date(), nullable=False),
    sa.Column('academic_year_id', sa.UUID(), nullable=True),
    sa.Column('admitted_academic_year_id', sa.UUID(), nullable=True),
    sa.Column('admitted_class_id', sa.UUID(), nullable=True),
    sa.Column('admitted_section_id', sa.UUID(), nullable=True),
    sa.Column('current_class_id', sa.UUID(), nullable=True),
    sa.Column('current_section_id', sa.UUID(), nullable=True),
    sa.Column('address_line1', sa.String(length=255), nullable=True),
    sa.Column('address_line2', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('is_previous_school', sa.Boolean(), nullable=True),
    sa.Column('previous_school_name', sa.String(length=255), nullable=True),
    sa.Column('previous_class', sa.String(length=50), nullable=True),
    sa.Column('previous_school_remark', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.id'], ),
    sa.ForeignKeyConstraint(['admitted_academic_year_id'], ['academic_years.id'], ),
    sa.ForeignKeyConstraint(['admitted_class_id'], ['classes.id'], ),
    sa.ForeignKeyConstraint(['admitted_section_id'], ['sections.id'], ),
    sa.ForeignKeyConstraint(['current_class_id'], ['classes.id'], ),
    sa.ForeignKeyConstraint(['current_section_id'], ['sections.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('admission_number')
    )
    op.create_index(op.f('ix_student_admissions_id'), 'student_admissions', ['id'], unique=True)

    op.create_table('student_attendance',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_attendance_id'), 'student_attendance', ['id'], unique=True)

    op.create_table('student_certificates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('certificate_type_id', sa.UUID(), nullable=True),
    sa.Column('issue_date', sa.Date(), nullable=True),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.Column('remarks', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['certificate_type_id'], ['certificate_types.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_certificates_id'), 'student_certificates', ['id'], unique=True)

    op.create_table('student_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('document_type', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('upload_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_documents_id'), 'student_documents', ['id'], unique=True)

    op.create_table('student_homework',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('submission_status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_homework_id'), 'student_homework', ['id'], unique=True)

    op.create_table('student_parent_links',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=True),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['parents.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_parent_links_id'), 'student_parent_links', ['id'], unique=True)

    op.create_table('student_transport_assignments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('trip_id', sa.UUID(), nullable=False),
    sa.Column('stop_id', sa.UUID(), nullable=False),
    sa.Column('fee_per_term', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['stop_id'], ['route_stops.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_transport_assignments_id'), 'student_transport_assignments', ['id'], unique=True)

    op.create_table('student_trips',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('trip_id', sa.UUID(), nullable=True),
    sa.Column('student_id', sa.UUID(), nullable=True),
    sa.Column('stop_id', sa.UUID(), nullable=True),
    sa.Column('fee_term_id', sa.UUID(), nullable=True),
    sa.Column('fee_per_term', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['fee_term_id'], ['fee_terms.id'], ),
    sa.ForeignKeyConstraint(['stop_id'], ['route_stops.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_trips_id'), 'student_trips', ['id'], unique=True)

    op.create_table('fee_class_map_term_amounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('fee_class_mapping_id', sa.UUID(), nullable=False),
    sa.Column('term_id', sa.UUID(), nullable=False),
    sa.Column('term_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['fee_class_mapping_id'], ['fee_class_mappings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['term_id'], ['fee_terms.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fee_class_mapping_id', 'term_id', name='uq_fee_class_mapping_term')
    )
    op.create_index(op.f('ix_fee_class_map_term_amounts_id'), 'fee_class_map_term_amounts', ['id'], unique=True)

    op.create_table('timetable_slots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('timetable_id', sa.UUID(), nullable=True),
    sa.Column('day', sa.String(), nullable=False),
    sa.Column('slot_time_id', sa.UUID(), nullable=True),
    sa.Column('is_break', sa.Boolean(), nullable=True),
    sa.Column('break_label', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['slot_time_id'], ['slot_times.id'], ),
    sa.ForeignKeyConstraint(['timetable_id'], ['timetables.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_timetable_slots_id'), 'timetable_slots', ['id'], unique=True)

    op.create_table('timetable_subject_options',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slot_id', sa.UUID(), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['slot_id'], ['timetable_slots.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_timetable_subject_options_id'), 'timetable_subject_options', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # (same as previous version; omitted here for brevity but preserved in file)
    op.drop_constraint(None, 'trips', type_='foreignkey')
    op.drop_constraint(None, 'trips', type_='foreignkey')
    op.drop_constraint(None, 'trips', type_='foreignkey')
    op.drop_index(op.f('ix_trips_id'), table_name='trips')
    op.create_index(op.f('ix_trips_id'), 'trips', ['id'], unique=False)
    op.alter_column('trips', 'driver_id', existing_type=sa.UUID(), type_=sa.INTEGER(), existing_nullable=True)
    op.alter_column('trips', 'route_id', existing_type=sa.UUID(), type_=sa.INTEGER(), existing_nullable=True)
    op.alter_column('trips', 'vehicle_id', existing_type=sa.UUID(), type_=sa.INTEGER(), existing_nullable=True)
    op.alter_column('trips', 'id', existing_type=sa.UUID(), type_=sa.INTEGER(), existing_nullable=False)
    op.drop_constraint(None, 'timetables', type_='foreignkey')
    op.drop_index(op.f('ix_timetables_id'), table_name='timetables')
    op.create_index(op.f('ix_timetables_id'), 'timetables', ['id'], unique=False)
    op.alter_column('timetables', 'section_id', existing_type=sa.UUID(), type_=sa.INTEGER(), existing_nullable=False)
    op.alter_column('timetables', 'id', existing_type=sa.UUID(), type_=sa.INTEGER(), existing_nullable=False)
    op.drop_constraint(None, 'slot_times', type_='foreignkey')
    op.drop_index(op.f('ix_slot_times_id'), table_name='slot_times')
    op.create_index(op.f('ix_slot_times_id'), 'slot_times', ['id'], unique=False)
    op.alter_column('slot_times', 'section_id', existing_type=sa.UUID(), type_=sa.INTEGER(), existing_nullable=False)
    op.alter_column('slot_times', 'id', existing_type=sa.UUID(), type_=sa.INTEGER(), existing_nullable=False)
    op.drop_constraint(None, 'route_stops', type_='foreignkey')
    op.drop_index(op.f('ix_route_stops_id'), table_name='route_stops')
    op.create_index(op.f('ix_route_stops_id'), 'route_stops', ['id'], unique=False)
    op.alter_column('route_stops', 'route_id', existing_type=sa.UUID(), type_=sa.INTEGER(), existing_nullable=True)
    op.alter_column('route_stops', 'id', existing_type=sa.UUID(), type_=sa.INTEGER(), existing_nullable=False)
    op.drop_index(op.f('ix_certificate_types_id'), table_name='certificate_types')
    op.create_index(op.f('ix_certificate_types_id'), 'certificate_types', ['id'], unique=False)
    op.alter_column('certificate_types', 'id', existing_type=sa.UUID(), type_=sa.INTEGER(), existing_nullable=False)
    op.drop_index(op.f('ix_timetable_subject_options_id'), table_name='timetable_subject_options')
    op.drop_table('timetable_subject_options')
    op.drop_index(op.f('ix_timetable_slots_id'), table_name='timetable_slots')
    op.drop_table('timetable_slots')
    op.drop_index(op.f('ix_fee_class_map_term_amounts_id'), table_name='fee_class_map_term_amounts')
    op.drop_table('fee_class_map_term_amounts')
    op.drop_index(op.f('ix_student_trips_id'), table_name='student_trips')
    op.drop_table('student_trips')
    op.drop_index(op.f('ix_student_transport_assignments_id'), table_name='student_transport_assignments')
    op.drop_table('student_transport_assignments')
    op.drop_index(op.f('ix_student_parent_links_id'), table_name='student_parent_links')
    op.drop_table('student_parent_links')
    op.drop_index(op.f('ix_student_homework_id'), table_name='student_homework')
    op.drop_table('student_homework')
    op.drop_index(op.f('ix_student_documents_id'), table_name='student_documents')
    op.drop_table('student_documents')
    op.drop_index(op.f('ix_student_certificates_id'), table_name='student_certificates')
    op.drop_table('student_certificates')
    op.drop_index(op.f('ix_student_attendance_id'), table_name='student_attendance')
    op.drop_table('student_attendance')
    op.drop_index(op.f('ix_student_admissions_id'), table_name='student_admissions')
    op.drop_table('student_admissions')
    op.drop_index(op.f('ix_staff_attendance_id'), table_name='staff_attendance')
    op.drop_table('staff_attendance')
    op.drop_index(op.f('ix_fee_class_mappings_id'), table_name='fee_class_mappings')
    op.drop_table('fee_class_mappings')
    op.drop_index(op.f('ix_students_id'), table_name='students')
    op.drop_table('students')
    op.drop_index(op.f('ix_staff_id'), table_name='staff')
    op.drop_table('staff')
    op.drop_index(op.f('ix_sections_id'), table_name='sections')
    op.drop_table('sections')
    op.drop_index(op.f('ix_parents_id'), table_name='parents')
    op.drop_table('parents')
    op.drop_index(op.f('ix_fee_types_id'), table_name='fee_types')
    op.drop_table('fee_types')
    op.drop_index(op.f('ix_fee_term_dates_term_id'), table_name='fee_term_dates')
    op.drop_index(op.f('ix_fee_term_dates_id'), table_name='fee_term_dates')
    op.drop_table('fee_term_dates')
    op.drop_index(op.f('ix_class_subject_mappings_id'), table_name='class_subject_mappings')
    op.drop_table('class_subject_mappings')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_subjects_id'), table_name='subjects')
    op.drop_table('subjects')
    op.drop_index(op.f('ix_role_menu_permissions_id'), table_name='role_menu_permissions')
    op.drop_table('role_menu_permissions')
    op.drop_index(op.f('ix_holidays_id'), table_name='holidays')
    op.drop_index(op.f('ix_holidays_academic_year_id'), table_name='holidays')
    op.drop_table('holidays')
    op.drop_index(op.f('ix_fee_terms_id'), table_name='fee_terms')
    op.drop_table('fee_terms')
    op.drop_index(op.f('ix_fee_categories_id'), table_name='fee_categories')
    op.drop_table('fee_categories')
    op.drop_index(op.f('ix_classes_id'), table_name='classes')
    op.drop_index(op.f('ix_classes_academic_year_id'), table_name='classes')
    op.drop_table('classes')
    op.drop_index(op.f('ix_vehicles_id'), table_name='vehicles')
    op.drop_table('vehicles')
    op.drop_index(op.f('ix_subject_categories_id'), table_name='subject_categories')
    op.drop_table('subject_categories')
    op.drop_index(op.f('ix_routes_id'), table_name='routes')
    op.drop_table('routes')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_menus_id'), table_name='menus')
    op.drop_table('menus')
    op.drop_index(op.f('ix_designations_id'), table_name='designations')
    op.drop_table('designations')
    op.drop_index(op.f('ix_academic_years_id'), table_name='academic_years')
    op.drop_table('academic_years')
