"""Add missing academic_years table

Revision ID: 19e502005e32
Revises: ac8a8190d7dc
Create Date: 2025-09-11 11:15:30.798394

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19e502005e32'
down_revision: Union[str, None] = 'ac8a8190d7dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fee_student_mappings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('student_admission_num', sa.String(length=50), nullable=False),
    sa.Column('class_id', sa.UUID(), nullable=False),
    sa.Column('section_id', sa.UUID(), nullable=False),
    sa.Column('fee_type_id', sa.UUID(), nullable=False),
    sa.Column('total_fee', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('academic_year_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.id'], ),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ),
    sa.ForeignKeyConstraint(['fee_type_id'], ['fee_types.id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ),
    sa.ForeignKeyConstraint(['student_admission_num'], ['student_admissions.admission_number'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'fee_type_id', 'academic_year_id', name='uq_student_fee_type_academic_year')
    )
    op.create_index(op.f('ix_fee_student_mappings_id'), 'fee_student_mappings', ['id'], unique=True)
    op.create_table('fee_student_map_term_amounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('fee_student_map_id', sa.UUID(), nullable=False),
    sa.Column('term_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('term_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['fee_student_map_id'], ['fee_student_mappings.id'], ),
    sa.ForeignKeyConstraint(['term_id'], ['fee_terms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fee_student_map_term_amounts_id'), 'fee_student_map_term_amounts', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fee_student_map_term_amounts_id'), table_name='fee_student_map_term_amounts')
    op.drop_table('fee_student_map_term_amounts')
    op.drop_index(op.f('ix_fee_student_mappings_id'), table_name='fee_student_mappings')
    op.drop_table('fee_student_mappings')
    # ### end Alembic commands ###
