"""Add fee_class_map_term_amounts table

Revision ID: 1f17f10c03ae
Revises: 600199c20eaf
Create Date: 2025-08-28 16:21:39.455509

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f17f10c03ae'
down_revision: Union[str, None] = '600199c20eaf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fee_class_map_term_amounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('fee_class_mapping_id', sa.UUID(), nullable=False),
    sa.Column('term_id', sa.UUID(), nullable=False),
    sa.Column('term_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['fee_class_mapping_id'], ['fee_class_mappings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['term_id'], ['fee_terms.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fee_class_mapping_id', 'term_id', name='uq_fee_class_mapping_term')
    )
    op.create_index(op.f('ix_fee_class_map_term_amounts_id'), 'fee_class_map_term_amounts', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fee_class_map_term_amounts_id'), table_name='fee_class_map_term_amounts')
    op.drop_table('fee_class_map_term_amounts')
    # ### end Alembic commands ###
