"""Add academic_year_id to classes

Revision ID: 2397c5a9e78e
Revises: 2c8021b74775
Create Date: 2025-06-25 00:25:49.330827

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2397c5a9e78e'
down_revision: Union[str, None] = '2c8021b74775'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('classes', sa.Column('academic_year_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_classes_academic_year_id'), 'classes', ['academic_year_id'], unique=False)
    op.create_foreign_key(None, 'classes', 'academic_years', ['academic_year_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'classes', type_='foreignkey')
    op.drop_index(op.f('ix_classes_academic_year_id'), table_name='classes')
    op.drop_column('classes', 'academic_year_id')
    # ### end Alembic commands ###
