"""Add new seperated tables 2

Revision ID: 5670fd1ff1b2
Revises: c0b5fc7618a1
Create Date: 2025-07-29 15:39:07.064742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5670fd1ff1b2'
down_revision: Union[str, None] = 'c0b5fc7618a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('certificate_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_certificate_types_id'), 'certificate_types', ['id'], unique=False)
    op.create_table('designations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_index(op.f('ix_designations_id'), 'designations', ['id'], unique=False)
    op.create_table('subject_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_subject_categories_id'), 'subject_categories', ['id'], unique=False)
    op.add_column('staff', sa.Column('designation_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'staff', 'designations', ['designation_id'], ['id'])
    op.drop_column('staff', 'designation')
    op.add_column('student_certificates', sa.Column('certificate_type_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'student_certificates', 'certificate_types', ['certificate_type_id'], ['id'])
    op.drop_column('student_certificates', 'certificate_type')
    op.add_column('subjects', sa.Column('category_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'subjects', 'subject_categories', ['category_id'], ['id'])
    op.drop_column('subjects', 'category')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subjects', sa.Column('category', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'subjects', type_='foreignkey')
    op.drop_column('subjects', 'category_id')
    op.add_column('student_certificates', sa.Column('certificate_type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'student_certificates', type_='foreignkey')
    op.drop_column('student_certificates', 'certificate_type_id')
    op.add_column('staff', sa.Column('designation', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'staff', type_='foreignkey')
    op.drop_column('staff', 'designation_id')
    op.drop_index(op.f('ix_subject_categories_id'), table_name='subject_categories')
    op.drop_table('subject_categories')
    op.drop_index(op.f('ix_designations_id'), table_name='designations')
    op.drop_table('designations')
    op.drop_index(op.f('ix_certificate_types_id'), table_name='certificate_types')
    op.drop_table('certificate_types')
    # ### end Alembic commands ###
