"""Add fee_class_mappings table

Revision ID: 600199c20eaf
Revises: 5262d183c37e
Create Date: 2025-08-28 14:03:57.708281

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '600199c20eaf'
down_revision: Union[str, None] = '5262d183c37e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fee_class_mappings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('fee_type_id', sa.UUID(), nullable=False),
    sa.Column('total_fee', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('academic_year_id', sa.Integer(), nullable=False),
    sa.Column('all_by_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.id'], ),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ),
    sa.ForeignKeyConstraint(['fee_type_id'], ['fee_types.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('class_id', 'fee_type_id', 'academic_year_id', name='uq_class_fee_type_academic_year')
    )
    op.create_index(op.f('ix_fee_class_mappings_id'), 'fee_class_mappings', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fee_class_mappings_id'), table_name='fee_class_mappings')
    op.drop_table('fee_class_mappings')
    # ### end Alembic commands ###
