"""Add few more Tables

Revision ID: 6b1dc0799b32
Revises: b1a239abde58
Create Date: 2025-06-24 23:30:23.524379

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b1dc0799b32'
down_revision: Union[str, None] = 'b1a239abde58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('class_subject_mappings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('academic_year_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.id'], ),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_class_subject_mappings_id'), 'class_subject_mappings', ['id'], unique=False)
    op.add_column('classes', sa.Column('academic_year_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_classes_academic_year_id'), 'classes', ['academic_year_id'], unique=False)
    op.create_foreign_key(None, 'classes', 'academic_years', ['academic_year_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'classes', type_='foreignkey')
    op.drop_index(op.f('ix_classes_academic_year_id'), table_name='classes')
    op.drop_column('classes', 'academic_year_id')
    op.drop_index(op.f('ix_class_subject_mappings_id'), table_name='class_subject_mappings')
    op.drop_table('class_subject_mappings')
    # ### end Alembic commands ###
