"""Add comprehensive multi-tenant permission system with plan-based access control

Revision ID: 537745ce58d5
Revises: 086e2d8cc398
Create Date: 2025-09-06 11:22:03.172413

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '537745ce58d5'
down_revision: Union[str, None] = '086e2d8cc398'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resource_permissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('resource', sa.String(length=50), nullable=False),
    sa.Column('action', sa.String(length=30), nullable=False),
    sa.Column('is_granted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_id', 'resource', 'action', name='unique_role_resource_action')
    )
    op.create_index(op.f('ix_resource_permissions_id'), 'resource_permissions', ['id'], unique=True)
    op.create_table('role_inheritance',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_role_id', sa.UUID(), nullable=False),
    sa.Column('public_role_template_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_role_id')
    )
    op.create_index(op.f('ix_role_inheritance_id'), 'role_inheritance', ['id'], unique=True)
    op.add_column('roles', sa.Column('is_system_role', sa.Boolean(), nullable=True))
    op.add_column('roles', sa.Column('is_custom_role', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('roles', 'is_custom_role')
    op.drop_column('roles', 'is_system_role')
    op.drop_index(op.f('ix_role_inheritance_id'), table_name='role_inheritance')
    op.drop_table('role_inheritance')
    op.drop_index(op.f('ix_resource_permissions_id'), table_name='resource_permissions')
    op.drop_table('resource_permissions')
    # ### end Alembic commands ###
