"""Add exclude_marks and order fields to class_subject_mappings

Revision ID: ac8a8190d7dc
Revises: 5280197d0edd
Create Date: 2025-09-09 21:22:16.074373

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac8a8190d7dc'
down_revision: Union[str, None] = '5280197d0edd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('class_subject_mappings', sa.Column('exclude_marks', sa.Boolean(), nullable=False))
    op.add_column('class_subject_mappings', sa.Column('order', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('class_subject_mappings', 'order')
    op.drop_column('class_subject_mappings', 'exclude_marks')
    # ### end Alembic commands ###
