"""Update staff tables 4

Revision ID: b8f0f6c727d7
Revises: 9ee9fbebd8b5
Create Date: 2025-07-17 16:58:25.768577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8f0f6c727d7'
down_revision: Union[str, None] = '9ee9fbebd8b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('staff', sa.Column('qualification', sa.String(length=100), nullable=True))
    op.add_column('staff', sa.Column('experience_years', sa.Integer(), nullable=True))
    op.add_column('staff', sa.Column('address', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('staff', 'address')
    op.drop_column('staff', 'experience_years')
    op.drop_column('staff', 'qualification')
    # ### end Alembic commands ###
