/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/_auth/forgot-password'
import { Route as AuthAuthRouteImport } from './routes/_auth/auth'
import { Route as AppStudentsRouteImport } from './routes/_app/students'
import { Route as AppAboutRouteImport } from './routes/_app/about'
import { Route as AppTimeTableRouteImport } from './routes/_app/TimeTable'
import { Route as AppCalenderRouteImport } from './routes/_app/Calender'
import { Route as AppTransportVehiclesRouteImport } from './routes/_app/transport/vehicles'
import { Route as AppTransportTripsRouteImport } from './routes/_app/transport/trips'
import { Route as AppTransportStudentTripsRouteImport } from './routes/_app/transport/studentTrips'
import { Route as AppTransportStudentTransportRouteImport } from './routes/_app/transport/studentTransport'
import { Route as AppTransportRoutesRouteImport } from './routes/_app/transport/routes'
import { Route as AppTransportRouteStopsRouteImport } from './routes/_app/transport/routeStops'
import { Route as AppStudentsCertificatesuploadRouteImport } from './routes/_app/students/certificatesupload'
import { Route as AppStudentsAttendanceRouteImport } from './routes/_app/students/attendance'
import { Route as AppStaffEnrollmentRouteImport } from './routes/_app/staff/enrollment'
import { Route as AppStaffAttendanceRouteImport } from './routes/_app/staff/attendance'
import { Route as AppMastersVehiclesRouteImport } from './routes/_app/masters/vehicles'
import { Route as AppMastersSubjectsRouteImport } from './routes/_app/masters/subjects'
import { Route as AppMastersRoutesRouteImport } from './routes/_app/masters/routes'
import { Route as AppMastersRouteStopsRouteImport } from './routes/_app/masters/routeStops'
import { Route as AppMastersHolidaysRouteImport } from './routes/_app/masters/holidays'
import { Route as AppMastersClassesandsectionsRouteImport } from './routes/_app/masters/classesandsections'
import { Route as AppMastersAcademicyearsRouteImport } from './routes/_app/masters/academicyears'

const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAuthRoute = AuthAuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => AuthRoute,
} as any)
const AppStudentsRoute = AppStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AppRoute,
} as any)
const AppAboutRoute = AppAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => AppRoute,
} as any)
const AppTimeTableRoute = AppTimeTableRouteImport.update({
  id: '/TimeTable',
  path: '/TimeTable',
  getParentRoute: () => AppRoute,
} as any)
const AppCalenderRoute = AppCalenderRouteImport.update({
  id: '/Calender',
  path: '/Calender',
  getParentRoute: () => AppRoute,
} as any)
const AppTransportVehiclesRoute = AppTransportVehiclesRouteImport.update({
  id: '/transport/vehicles',
  path: '/transport/vehicles',
  getParentRoute: () => AppRoute,
} as any)
const AppTransportTripsRoute = AppTransportTripsRouteImport.update({
  id: '/transport/trips',
  path: '/transport/trips',
  getParentRoute: () => AppRoute,
} as any)
const AppTransportStudentTripsRoute =
  AppTransportStudentTripsRouteImport.update({
    id: '/transport/studentTrips',
    path: '/transport/studentTrips',
    getParentRoute: () => AppRoute,
  } as any)
const AppTransportStudentTransportRoute =
  AppTransportStudentTransportRouteImport.update({
    id: '/transport/studentTransport',
    path: '/transport/studentTransport',
    getParentRoute: () => AppRoute,
  } as any)
const AppTransportRoutesRoute = AppTransportRoutesRouteImport.update({
  id: '/transport/routes',
  path: '/transport/routes',
  getParentRoute: () => AppRoute,
} as any)
const AppTransportRouteStopsRoute = AppTransportRouteStopsRouteImport.update({
  id: '/transport/routeStops',
  path: '/transport/routeStops',
  getParentRoute: () => AppRoute,
} as any)
const AppStudentsCertificatesuploadRoute =
  AppStudentsCertificatesuploadRouteImport.update({
    id: '/certificatesupload',
    path: '/certificatesupload',
    getParentRoute: () => AppStudentsRoute,
  } as any)
const AppStudentsAttendanceRoute = AppStudentsAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AppStudentsRoute,
} as any)
const AppStaffEnrollmentRoute = AppStaffEnrollmentRouteImport.update({
  id: '/staff/enrollment',
  path: '/staff/enrollment',
  getParentRoute: () => AppRoute,
} as any)
const AppStaffAttendanceRoute = AppStaffAttendanceRouteImport.update({
  id: '/staff/attendance',
  path: '/staff/attendance',
  getParentRoute: () => AppRoute,
} as any)
const AppMastersVehiclesRoute = AppMastersVehiclesRouteImport.update({
  id: '/masters/vehicles',
  path: '/masters/vehicles',
  getParentRoute: () => AppRoute,
} as any)
const AppMastersSubjectsRoute = AppMastersSubjectsRouteImport.update({
  id: '/masters/subjects',
  path: '/masters/subjects',
  getParentRoute: () => AppRoute,
} as any)
const AppMastersRoutesRoute = AppMastersRoutesRouteImport.update({
  id: '/masters/routes',
  path: '/masters/routes',
  getParentRoute: () => AppRoute,
} as any)
const AppMastersRouteStopsRoute = AppMastersRouteStopsRouteImport.update({
  id: '/masters/routeStops',
  path: '/masters/routeStops',
  getParentRoute: () => AppRoute,
} as any)
const AppMastersHolidaysRoute = AppMastersHolidaysRouteImport.update({
  id: '/masters/holidays',
  path: '/masters/holidays',
  getParentRoute: () => AppRoute,
} as any)
const AppMastersClassesandsectionsRoute =
  AppMastersClassesandsectionsRouteImport.update({
    id: '/masters/classesandsections',
    path: '/masters/classesandsections',
    getParentRoute: () => AppRoute,
  } as any)
const AppMastersAcademicyearsRoute = AppMastersAcademicyearsRouteImport.update({
  id: '/masters/academicyears',
  path: '/masters/academicyears',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/Calender': typeof AppCalenderRoute
  '/TimeTable': typeof AppTimeTableRoute
  '/about': typeof AppAboutRoute
  '/students': typeof AppStudentsRouteWithChildren
  '/auth': typeof AuthAuthRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/': typeof AppIndexRoute
  '/masters/academicyears': typeof AppMastersAcademicyearsRoute
  '/masters/classesandsections': typeof AppMastersClassesandsectionsRoute
  '/masters/holidays': typeof AppMastersHolidaysRoute
  '/masters/routeStops': typeof AppMastersRouteStopsRoute
  '/masters/routes': typeof AppMastersRoutesRoute
  '/masters/subjects': typeof AppMastersSubjectsRoute
  '/masters/vehicles': typeof AppMastersVehiclesRoute
  '/staff/attendance': typeof AppStaffAttendanceRoute
  '/staff/enrollment': typeof AppStaffEnrollmentRoute
  '/students/attendance': typeof AppStudentsAttendanceRoute
  '/students/certificatesupload': typeof AppStudentsCertificatesuploadRoute
  '/transport/routeStops': typeof AppTransportRouteStopsRoute
  '/transport/routes': typeof AppTransportRoutesRoute
  '/transport/studentTransport': typeof AppTransportStudentTransportRoute
  '/transport/studentTrips': typeof AppTransportStudentTripsRoute
  '/transport/trips': typeof AppTransportTripsRoute
  '/transport/vehicles': typeof AppTransportVehiclesRoute
}
export interface FileRoutesByTo {
  '/Calender': typeof AppCalenderRoute
  '/TimeTable': typeof AppTimeTableRoute
  '/about': typeof AppAboutRoute
  '/students': typeof AppStudentsRouteWithChildren
  '/auth': typeof AuthAuthRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/': typeof AppIndexRoute
  '/masters/academicyears': typeof AppMastersAcademicyearsRoute
  '/masters/classesandsections': typeof AppMastersClassesandsectionsRoute
  '/masters/holidays': typeof AppMastersHolidaysRoute
  '/masters/routeStops': typeof AppMastersRouteStopsRoute
  '/masters/routes': typeof AppMastersRoutesRoute
  '/masters/subjects': typeof AppMastersSubjectsRoute
  '/masters/vehicles': typeof AppMastersVehiclesRoute
  '/staff/attendance': typeof AppStaffAttendanceRoute
  '/staff/enrollment': typeof AppStaffEnrollmentRoute
  '/students/attendance': typeof AppStudentsAttendanceRoute
  '/students/certificatesupload': typeof AppStudentsCertificatesuploadRoute
  '/transport/routeStops': typeof AppTransportRouteStopsRoute
  '/transport/routes': typeof AppTransportRoutesRoute
  '/transport/studentTransport': typeof AppTransportStudentTransportRoute
  '/transport/studentTrips': typeof AppTransportStudentTripsRoute
  '/transport/trips': typeof AppTransportTripsRoute
  '/transport/vehicles': typeof AppTransportVehiclesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/_app/Calender': typeof AppCalenderRoute
  '/_app/TimeTable': typeof AppTimeTableRoute
  '/_app/about': typeof AppAboutRoute
  '/_app/students': typeof AppStudentsRouteWithChildren
  '/_auth/auth': typeof AuthAuthRoute
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_app/': typeof AppIndexRoute
  '/_app/masters/academicyears': typeof AppMastersAcademicyearsRoute
  '/_app/masters/classesandsections': typeof AppMastersClassesandsectionsRoute
  '/_app/masters/holidays': typeof AppMastersHolidaysRoute
  '/_app/masters/routeStops': typeof AppMastersRouteStopsRoute
  '/_app/masters/routes': typeof AppMastersRoutesRoute
  '/_app/masters/subjects': typeof AppMastersSubjectsRoute
  '/_app/masters/vehicles': typeof AppMastersVehiclesRoute
  '/_app/staff/attendance': typeof AppStaffAttendanceRoute
  '/_app/staff/enrollment': typeof AppStaffEnrollmentRoute
  '/_app/students/attendance': typeof AppStudentsAttendanceRoute
  '/_app/students/certificatesupload': typeof AppStudentsCertificatesuploadRoute
  '/_app/transport/routeStops': typeof AppTransportRouteStopsRoute
  '/_app/transport/routes': typeof AppTransportRoutesRoute
  '/_app/transport/studentTransport': typeof AppTransportStudentTransportRoute
  '/_app/transport/studentTrips': typeof AppTransportStudentTripsRoute
  '/_app/transport/trips': typeof AppTransportTripsRoute
  '/_app/transport/vehicles': typeof AppTransportVehiclesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/Calender'
    | '/TimeTable'
    | '/about'
    | '/students'
    | '/auth'
    | '/forgot-password'
    | '/login'
    | '/'
    | '/masters/academicyears'
    | '/masters/classesandsections'
    | '/masters/holidays'
    | '/masters/routeStops'
    | '/masters/routes'
    | '/masters/subjects'
    | '/masters/vehicles'
    | '/staff/attendance'
    | '/staff/enrollment'
    | '/students/attendance'
    | '/students/certificatesupload'
    | '/transport/routeStops'
    | '/transport/routes'
    | '/transport/studentTransport'
    | '/transport/studentTrips'
    | '/transport/trips'
    | '/transport/vehicles'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/Calender'
    | '/TimeTable'
    | '/about'
    | '/students'
    | '/auth'
    | '/forgot-password'
    | '/login'
    | '/'
    | '/masters/academicyears'
    | '/masters/classesandsections'
    | '/masters/holidays'
    | '/masters/routeStops'
    | '/masters/routes'
    | '/masters/subjects'
    | '/masters/vehicles'
    | '/staff/attendance'
    | '/staff/enrollment'
    | '/students/attendance'
    | '/students/certificatesupload'
    | '/transport/routeStops'
    | '/transport/routes'
    | '/transport/studentTransport'
    | '/transport/studentTrips'
    | '/transport/trips'
    | '/transport/vehicles'
  id:
    | '__root__'
    | '/_app'
    | '/_auth'
    | '/_app/Calender'
    | '/_app/TimeTable'
    | '/_app/about'
    | '/_app/students'
    | '/_auth/auth'
    | '/_auth/forgot-password'
    | '/_auth/login'
    | '/_app/'
    | '/_app/masters/academicyears'
    | '/_app/masters/classesandsections'
    | '/_app/masters/holidays'
    | '/_app/masters/routeStops'
    | '/_app/masters/routes'
    | '/_app/masters/subjects'
    | '/_app/masters/vehicles'
    | '/_app/staff/attendance'
    | '/_app/staff/enrollment'
    | '/_app/students/attendance'
    | '/_app/students/certificatesupload'
    | '/_app/transport/routeStops'
    | '/_app/transport/routes'
    | '/_app/transport/studentTransport'
    | '/_app/transport/studentTrips'
    | '/_app/transport/trips'
    | '/_app/transport/vehicles'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/auth': {
      id: '/_auth/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthAuthRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/students': {
      id: '/_app/students'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof AppStudentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/about': {
      id: '/_app/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AppAboutRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/TimeTable': {
      id: '/_app/TimeTable'
      path: '/TimeTable'
      fullPath: '/TimeTable'
      preLoaderRoute: typeof AppTimeTableRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/Calender': {
      id: '/_app/Calender'
      path: '/Calender'
      fullPath: '/Calender'
      preLoaderRoute: typeof AppCalenderRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/transport/vehicles': {
      id: '/_app/transport/vehicles'
      path: '/transport/vehicles'
      fullPath: '/transport/vehicles'
      preLoaderRoute: typeof AppTransportVehiclesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/transport/trips': {
      id: '/_app/transport/trips'
      path: '/transport/trips'
      fullPath: '/transport/trips'
      preLoaderRoute: typeof AppTransportTripsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/transport/studentTrips': {
      id: '/_app/transport/studentTrips'
      path: '/transport/studentTrips'
      fullPath: '/transport/studentTrips'
      preLoaderRoute: typeof AppTransportStudentTripsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/transport/studentTransport': {
      id: '/_app/transport/studentTransport'
      path: '/transport/studentTransport'
      fullPath: '/transport/studentTransport'
      preLoaderRoute: typeof AppTransportStudentTransportRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/transport/routes': {
      id: '/_app/transport/routes'
      path: '/transport/routes'
      fullPath: '/transport/routes'
      preLoaderRoute: typeof AppTransportRoutesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/transport/routeStops': {
      id: '/_app/transport/routeStops'
      path: '/transport/routeStops'
      fullPath: '/transport/routeStops'
      preLoaderRoute: typeof AppTransportRouteStopsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/students/certificatesupload': {
      id: '/_app/students/certificatesupload'
      path: '/certificatesupload'
      fullPath: '/students/certificatesupload'
      preLoaderRoute: typeof AppStudentsCertificatesuploadRouteImport
      parentRoute: typeof AppStudentsRoute
    }
    '/_app/students/attendance': {
      id: '/_app/students/attendance'
      path: '/attendance'
      fullPath: '/students/attendance'
      preLoaderRoute: typeof AppStudentsAttendanceRouteImport
      parentRoute: typeof AppStudentsRoute
    }
    '/_app/staff/enrollment': {
      id: '/_app/staff/enrollment'
      path: '/staff/enrollment'
      fullPath: '/staff/enrollment'
      preLoaderRoute: typeof AppStaffEnrollmentRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/staff/attendance': {
      id: '/_app/staff/attendance'
      path: '/staff/attendance'
      fullPath: '/staff/attendance'
      preLoaderRoute: typeof AppStaffAttendanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/masters/vehicles': {
      id: '/_app/masters/vehicles'
      path: '/masters/vehicles'
      fullPath: '/masters/vehicles'
      preLoaderRoute: typeof AppMastersVehiclesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/masters/subjects': {
      id: '/_app/masters/subjects'
      path: '/masters/subjects'
      fullPath: '/masters/subjects'
      preLoaderRoute: typeof AppMastersSubjectsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/masters/routes': {
      id: '/_app/masters/routes'
      path: '/masters/routes'
      fullPath: '/masters/routes'
      preLoaderRoute: typeof AppMastersRoutesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/masters/routeStops': {
      id: '/_app/masters/routeStops'
      path: '/masters/routeStops'
      fullPath: '/masters/routeStops'
      preLoaderRoute: typeof AppMastersRouteStopsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/masters/holidays': {
      id: '/_app/masters/holidays'
      path: '/masters/holidays'
      fullPath: '/masters/holidays'
      preLoaderRoute: typeof AppMastersHolidaysRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/masters/classesandsections': {
      id: '/_app/masters/classesandsections'
      path: '/masters/classesandsections'
      fullPath: '/masters/classesandsections'
      preLoaderRoute: typeof AppMastersClassesandsectionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/masters/academicyears': {
      id: '/_app/masters/academicyears'
      path: '/masters/academicyears'
      fullPath: '/masters/academicyears'
      preLoaderRoute: typeof AppMastersAcademicyearsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppStudentsRouteChildren {
  AppStudentsAttendanceRoute: typeof AppStudentsAttendanceRoute
  AppStudentsCertificatesuploadRoute: typeof AppStudentsCertificatesuploadRoute
}

const AppStudentsRouteChildren: AppStudentsRouteChildren = {
  AppStudentsAttendanceRoute: AppStudentsAttendanceRoute,
  AppStudentsCertificatesuploadRoute: AppStudentsCertificatesuploadRoute,
}

const AppStudentsRouteWithChildren = AppStudentsRoute._addFileChildren(
  AppStudentsRouteChildren,
)

interface AppRouteChildren {
  AppCalenderRoute: typeof AppCalenderRoute
  AppTimeTableRoute: typeof AppTimeTableRoute
  AppAboutRoute: typeof AppAboutRoute
  AppStudentsRoute: typeof AppStudentsRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
  AppMastersAcademicyearsRoute: typeof AppMastersAcademicyearsRoute
  AppMastersClassesandsectionsRoute: typeof AppMastersClassesandsectionsRoute
  AppMastersHolidaysRoute: typeof AppMastersHolidaysRoute
  AppMastersRouteStopsRoute: typeof AppMastersRouteStopsRoute
  AppMastersRoutesRoute: typeof AppMastersRoutesRoute
  AppMastersSubjectsRoute: typeof AppMastersSubjectsRoute
  AppMastersVehiclesRoute: typeof AppMastersVehiclesRoute
  AppStaffAttendanceRoute: typeof AppStaffAttendanceRoute
  AppStaffEnrollmentRoute: typeof AppStaffEnrollmentRoute
  AppTransportRouteStopsRoute: typeof AppTransportRouteStopsRoute
  AppTransportRoutesRoute: typeof AppTransportRoutesRoute
  AppTransportStudentTransportRoute: typeof AppTransportStudentTransportRoute
  AppTransportStudentTripsRoute: typeof AppTransportStudentTripsRoute
  AppTransportTripsRoute: typeof AppTransportTripsRoute
  AppTransportVehiclesRoute: typeof AppTransportVehiclesRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCalenderRoute: AppCalenderRoute,
  AppTimeTableRoute: AppTimeTableRoute,
  AppAboutRoute: AppAboutRoute,
  AppStudentsRoute: AppStudentsRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
  AppMastersAcademicyearsRoute: AppMastersAcademicyearsRoute,
  AppMastersClassesandsectionsRoute: AppMastersClassesandsectionsRoute,
  AppMastersHolidaysRoute: AppMastersHolidaysRoute,
  AppMastersRouteStopsRoute: AppMastersRouteStopsRoute,
  AppMastersRoutesRoute: AppMastersRoutesRoute,
  AppMastersSubjectsRoute: AppMastersSubjectsRoute,
  AppMastersVehiclesRoute: AppMastersVehiclesRoute,
  AppStaffAttendanceRoute: AppStaffAttendanceRoute,
  AppStaffEnrollmentRoute: AppStaffEnrollmentRoute,
  AppTransportRouteStopsRoute: AppTransportRouteStopsRoute,
  AppTransportRoutesRoute: AppTransportRoutesRoute,
  AppTransportStudentTransportRoute: AppTransportStudentTransportRoute,
  AppTransportStudentTripsRoute: AppTransportStudentTripsRoute,
  AppTransportTripsRoute: AppTransportTripsRoute,
  AppTransportVehiclesRoute: AppTransportVehiclesRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthAuthRoute: typeof AuthAuthRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthAuthRoute: AuthAuthRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
